### ISSUE TITLE
Birthday contacts

### ISSUE THREAD

**Issue by plegrand1** [Etar-Group/Etar-Calendar#1020]
Hello,
 Could someone please explain to me why some of my android contacts are not showing up in etar? 
 Some contacts are showing up and some are not. I can't see what makes them different
I must add that I do not synchronize my contacts with google
Many thanks for help

**Comment by jspricke** [comment]
Sounds like what I suggested in my first answer ;).
And no worries about the pollution, that's why I closed it directly ;).
