### ISSUE TITLE
Etar crashes on Samsung devices

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [Etar-Group/Etar-Calendar#1032]
Etar crashed on two different Samsung devices for me. The only similarity between the two is both has been debloated with this tool: https://github.com/0x192/universal-android-debloater
Can someone with a vanilla Samsung device check if this happens to the also?

What dependency does Etar have that might have been removed by the script?

**Comment by jspricke** [comment]
Probably at least this: https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L7007

**Comment by IHateTheProgrammingClass** [comment]
Yes I'm 99% sure that is the problem. I will check and reopen the issue if the problem still exists. Thank you.
