### ISSUE TITLE
no notifications in 1.0.27

### ISSUE THREAD

**Issue by AaronM04** [Etar-Group/Etar-Calendar#1068]
Hi, I got notifications for calendar events in 1.0.26. I upgraded to 1.0.27 this morning via f-droid and I don't get any at all.

**Comment by jspricke** [comment]
duplicate of #1064

**Comment by AaronM04** [comment]
What's worse, I tried to downgrade and I got a popup "Failed to install due to an unknown error".

**Comment by jspricke** [comment]
known Android limitation.

**Comment by 4181715** [comment]
> 

You need to uninstall version 1.0.27 and then install version 1.0.26.
