### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [Etar-Group/Etar-Calendar#1086]
According to https://github.com/Etar-Group/Etar-Calendar/search?q=any+later
https://hosted.weblate.org/projects/etar-calendar/strings/#information
and https://hosted.weblate.org/projects/etar-calendar/metadata/#information
should be GPLv3-**or later**.

This can be changed in
https://hosted.weblate.org/settings/etar-calendar/strings/
and https://hosted.weblate.org/settings/etar-calendar/metadata

ideally also the glossary
https://hosted.weblate.org/settings/etar-calendar/glossary/

**Comment by jspricke** [comment]
fixed, thx.
