### ISSUE TITLE
Feature request: disable reminders for defined calendars

### ISSUE THREAD

**Issue by glemco** [Etar-Group/Etar-Calendar#1107]
Some desktop based calendars (e.g. Evolution) allow to disable reminders just for some specific calendars. I found it handy for big shared calendars where I would get notifications for events I'm not invited to (I know that could possibly be solved server side), sometimes even accidentally modifying those events.
I couldn't find a similar feature in Etar, I guess it wouldn't be so complex to use the built-in notifications categories, so that users would be able to set importance and other properties _by calendar_ rather than for all the notifications together.
Thanks in advance for this and for the great work!

**Comment by spacekpe** [comment]
FTR another Android calendaring app implements this using Android notification categories, i.e. no UI in the app itself.

See https://github.com/SimpleMobileTools/Simple-Calendar/issues/1003 for details. Luckily both projects are GPL-3 licensed, so there might be an opportunity to learn from their code.

I hope it helps.

**Comment by akki42** [comment]
This has been requested / discussed for years. Please see https://github.com/Etar-Group/Etar-Calendar/issues/67 and https://github.com/Etar-Group/Etar-Calendar/issues/783.

**Comment by glemco** [comment]
Alright, I didn't find those issues at the time I opened this, closing as duplicate
