### ISSUE TITLE
Colour change of single events does not work

### ISSUE THREAD

**Issue by 34dihydroxyphentylamine** [Etar-Group/Etar-Calendar#1134]
After creating an event, when I try to change colour from default and click on the colour pallet button, there shows a blank loading window and nothing more.

Issue on: Android 9 PKQ1.181021.001 with MIUI Global 11.0.11

**Comment by Epse** [comment]
Same issue on Android 13, Samsung and Motorola. I missed this issue when searching so I duplicated it in #1276

**Comment by Epse** [comment]
@34dihydroxyphentylamine is your calendar synced by DAVx5? You need to enable colour support in account settings, this fixed it for me.

**Comment by olbotta** [comment]
@Epse it is definetly the solution, it worked for me
