### ISSUE TITLE
Event Display Lag in Day View When Scrolling a Few Day Ahead or Behind

### ISSUE THREAD

**Issue by landry314** [Etar-Group/Etar-Calendar#1194]
I have a tremendous display lag when I scroll in Day View a few days ahead or behind. I see an empty day when I know there are events there and they won't appear until I back out of the app then come right back in and then they refresh. If I wait, sometimes it takes 20 seconds to display the events on a day but sometimes it never does and I still have to back out of the app and come back in. The refresh option in the menu does nothing.

I deleted the data for the app and that fixed it for a few days then it became massively lagged again.

This is really annoying. I tried enabling contacts permission but that didn't work. I wonder why the refresh on new days a few days later or earlier is sooooo slow. Any one else having this problem?

This might be related to issue #434

I am using version 1.0.30 on LineageOS 19.1. It was happening on a Pixel 3 and now a Pixel 5 too.

**Comment by jchamml** [comment]
I also have this problem on Nokia 8.3

**Comment by landry314** [comment]
this is a really bad bug. i am constantly backing out of the app and coming back to cause a refresh of the day view when i scroll a few days ahead or behind and nothing displays.

**Comment by landry314** [comment]
debug version does NOT work. i noticed that the day view display error is also happening in week view in the same way.

**Comment by landry314** [comment]
OH WAIT, it is ANOTHER problem with the "Use home time zone" setting. After turning this setting off, everything is fine. the debug version is working.
