### ISSUE TITLE
Tablet text not readable in dark/black mode

### ISSUE THREAD

**Issue by mxsrm** [Etar-Group/Etar-Calendar#1228]
Newest version from Play Store dating today.

When using dark or black mode in a tablet you can not read the name of the active calendars. Screenshot attached.

![Screenshot_20220903_090515_Etar](https://user-images.githubusercontent.com/7951225/188279482-a2f2d0c6-c70e-4244-9c5b-352426da12db.jpg)

**Comment by obifur** [comment]
dupe of #978

**Comment by mxsrm** [comment]
Even worse, that bug is open for more than 1 year now...

**Comment by mxsrm** [comment]
Since no one cares, closed.
