### ISSUE TITLE
[feature request] Shortcut or widget to add an event

### ISSUE THREAD

**Issue by opk12** [Etar-Group/Etar-Calendar#1233]
The calendar widget has a button to add an event (#1106). I am not using the widget, because it would be distracting and take screen space.

I just need a shortcut, or 1x1-sized widget, that opens a window to add a task. When the task is added, the window should delete itself, so the Recent Apps list is not cluttered.

**Comment by jspricke** [comment]
long press on the Etar icon

**Comment by opk12** [comment]
@jspricke It shows the usual Android context menu with no option to touch the calendar, just
- Select multiple items
- Remove shortcut
- Uninstall
- App info

I am on Android 7.1 on a Samsung phone.

**Comment by opk12** [comment]
For posterity, [Shortcuts for Calendar/Contacts](https://f-droid.org/de/packages/org.shortcuts/) from f-droid does the job.
