### ISSUE TITLE
Go to... goes to an incorrect week

### ISSUE THREAD

**Issue by Yenya** [Etar-Group/Etar-Calendar#1251]
When I use `Go to ...` from the three dots menu, it often goes to a different date than what I selected. E.g. now I have Etar in the week view, select November 25, and the week starting at November 14 ending at November 20 gets displayed.

I think the offset is usually -1 week, but I have seen different offsets as well as the correct week.

Etar 1.0.30 from F-Droid.

**Comment by tribin** [comment]
Using "Go to..." from the three dots menu, each time I select a certain day, regardless if in the past or the future, Etar jumps to the day exactly >> four weeks after << the one I selected.
Using Etar 1.0.34 from F-Droid 1.16.3 on Android 8.0.0.
Anyway, thanks a lot for this fine and very useful App!

**Comment by hartwork** [comment]
Same with Etar 1.0.34.

@etar-group please get in touch via my profile e-mail if there is interest in financial support for a timely bugfix and bugfix release for this issue.

**Comment by jrcarter** [comment]
I have the Etar that comes with /e/ OS 1.16-S (Calendar "Version 12"). When I select a date in the future from "Go to ..." it takes me to the first date in the future on the same day of the week as the date I entered. For example, if today, Tuesday 2023-11-07, I say go to Thursday 2023-11-16, it takes me to Thursday 2023-11-09.

**Comment by hartwork** [comment]
With Etar 1.0.36 now it seems to always jump to the current week, no matter what day I pick in the Go-To dialog.

I can only repeat sponsoring offer from earlier:

> Please get in touch via my profile e-mail if there is interest in financial support for a timely bugfix and bugfix release for this issue.

CC @Gitsaibot @jspricke
