### ISSUE TITLE
Import multiple events from ICS files

### ISSUE THREAD

**Issue by jluttine** [Etar-Group/Etar-Calendar#1316]
ICS calendar files may contain multiple events. However, when importing the file with Etar, only one (the first?) event is imported and the others ignored. Etar should import all those events.

**Comment by LRN** [comment]
I second this issue. After installing new LineageOS i've switched from Simple Calendar to Etar, which comes with LOS preinstalled. I've exported all of the events from SC into one ICS file, but can't import all of them into Etar, because Etar only takes the first event in the file.
Installing rparkins999/Etar-Calendar is not an option, since i have to build it first, which is not a trivial affair for me.

**Comment by woheller69** [comment]
you can use this app:

https://f-droid.org/packages/org.sufficientlysecure.ical/

**Comment by jluttine** [comment]
> you can use this app:
> 
> https://f-droid.org/packages/org.sufficientlysecure.ical/

Yeah, that's one option. A problem with that app is that the imported calendar events can't be modified whereas Etar-imported events can be modified.

I think the UI in Etar could be such that when importing a file with multiple events, Etar just asks which calendar to import them into and then imports without opening the events. One can then find and edit the events in the calendar if needed. That'd be pretty simple and would work for large amounts of events. That's similar to how the linked app mentioned above works.

**Comment by woheller69** [comment]
I have no problem modifying imported events from https://f-droid.org/packages/org.sufficientlysecure.ical/

**Comment by foxyseta** [comment]
I also second this. Apparently OP isn't available to lift @rparkins999's code at the moment?

**Comment by rparkins999** [comment]
I had a big ics file to import, so I just tried it with <code>rparkins999/Etar-Calendar</code> and it didn't work 😞.

I'll try to fix the code in <code>rparkins999/Etar-Calendar</code> as soon as I can, but I don't exercise it very often as I only import a big ics file about twice per year.

Another option, if the calendar on your phone is synchronised to a PC, is to import the ics file into your PC and then synchronise. Most PC calendars will read a whole ics file. Evolution, which I use, successfully did so.

**Comment by Ekleog** [comment]
I think this was not actually fixed by #1700? On 1.0.48, when I import ICS files shared from train/airline apps, I still only get the first trip added to my calendar.

And for those ICS files unfortunately the app listed does not work, as it seems to not be recognized as a sharing target.

**Comment by jluttine** [comment]
Yes, as far as I understand, #1700 only added support for a recurring event, not having multiple events in a single ICS file. So, I think this issue should be re-opened.
