### ISSUE TITLE
Phone call permission

### ISSUE THREAD

**Issue by RoobinCoder** [Etar-Group/Etar-Calendar#1328]
Hi,
I am using Etar. In the App info and permissions section, I saw phone permission. I search in the code there is no runtime permission for phone call and no phone permission exists in manifests.
There is also intent that has phone call action but for this kind of action there is no need for such permission. I wanna know what these permission is for.
Thank you.

**Comment by jspricke** [comment]
I don't see that, can you send a screen shot?

**Comment by RoobinCoder** [comment]
![image](https://user-images.githubusercontent.com/115070890/214265547-61297d29-7990-4193-a8fe-3dbca32700f7.png)

**Comment by jspricke** [comment]
Interesting, which Etar version? From where did you get it? Which Android version? Which Phone?

**Comment by RoobinCoder** [comment]
Etar version: 1.0.30
android version: 10
phone: samsung M20

**Comment by jspricke** [comment]
Can you try the latest version 1.0.34, available on F-Droid: https://f-droid.org/de/packages/ws.xsoh.etar/

**Comment by jspricke** [comment]
It may be related to the vibration alarm.

**Comment by RoobinCoder** [comment]
OK, I will check

**Comment by RoobinCoder** [comment]
You are right. there is no phone permission in new version.
thanks.
