### ISSUE TITLE
Add already existing account from DAVx5

### ISSUE THREAD

**Issue by JBlocklove** [Etar-Group/Etar-Calendar#1342]
I already linked a DAVx5 account to my nextcloud server and now I'm trying to add it to Etar, but when I click to add an account it takes me to a page to actually create a new account, not just point Etar to the one that's already linked. Is there a way to do this or do I need to delete the DAVx5 account and create it through Etar? Not a huge problem for me either way, I just figured it's worth asking.

**Comment by jspricke** [comment]
You don't need to do anything, Etar should simply show the calendar entries. Also see: https://github.com/Etar-Group/Etar-Calendar#technical-explanation

**Comment by JBlocklove** [comment]
Wow thanks for the fast response! Looks like I just needed to force DAVx5 to sync again for it to show up. Thanks!
