### ISSUE TITLE
wrong italian text in event's recurring pane

### ISSUE THREAD

**Issue by e075e** [Etar-Group/Etar-Calendar#1343]
Hi,
I have etar set in Italian language, so this I am not sure if this bug is present in the English localization, and command name stated here could be different

1. create a new appointment pressing the + button
2. enable the “recurring” tab by pressing on occasional event
3. enable slider to make it recurring
4. default is weekly, switch to yearly

the text now shows "ogni 1 settimana" which means "Every 1 week", instead of
```
singular: "ogni 1 anno"
plural: "ogni 2 anni", etc
```

the same pattern happens if you switch to daily or monthly and then to yearly again:

daily -> yearly
Yearly now shows "Ogni 1 giorno" instead of "Ogni 1 anno"

monthly -> yearly
Yearly now shows "Ogni 1 mese" instead of "Ogni 1 anno"

![Screenshot_2023-02-18-10-07-03-83](https://user-images.githubusercontent.com/15078341/220358144-cb763a2f-983d-431e-83d2-c3ccd02327f8.jpg)
![Screenshot_2023-02-18-10-07-31-50](https://user-images.githubusercontent.com/15078341/220358201-c4544565-5e59-4800-97f2-54103e697cef.jpg)
![Screenshot_2023-02-18-10-07-40-27](https://user-images.githubusercontent.com/15078341/220358205-57929681-04de-4d72-8c2e-60936cdb5db7.jpg)

**Comment by jspricke** [comment]
The Etar translation is managed via Weblate. Can you simply log in there and change it? https://github.com/Etar-Group/Etar-Calendar#translations

Thanks!

**Comment by jspricke** [comment]
Then it should be correct in the latest version (1.0.34). Which Etar version do you use?
