### ISSUE TITLE
Sync activation deletes offline calendar entries

### ISSUE THREAD

**Issue by zakmac1** [Etar-Group/Etar-Calendar#1352]
Hello,
a year ago I installed Etar on a new Android 11 phone and synced entries from my google account to it. Then I disabled the network connection / sync option and used it offline for adding entries until now.
Today I enabled sync and network again, I thought it would backup all calendar entries of the past year to the cloud. But instead all entries have disappeard on the phone after enabling the sync. 
In the cloud I see entries until a year ago. Which I now also don't see on the phone.
Anything I can do to get my offline entries back?
Thanks

**Comment by jspricke** [comment]
I'm sorry to hear but that is most likely a problem with your sync app and not Etar. See here for a technical explanation: https://github.com/Etar-Group/Etar-Calendar#how-to-use-etar
Recovering your data also depend a lot on which apps and servers you used and thus nothing we can support here.
