### ISSUE TITLE
Notification sound delayed

### ISSUE THREAD

**Issue by sebaFlame** [Etar-Group/Etar-Calendar#1356]
I'm using Android 10 with One UI 2.0 on a Samsung Galaxy A6 (an Exynos)

When I'm setting reminders (alarms) the alarm (through AlarmManager) goes off at exactly the correct time. Then the screen gets updated and a notification starts to play. This last step gets interrupted after about 1 second and resumes 1 to 5 minutes later. I assume those are doze maintenance windows. This log reflects what I'm seeing. The reminder was set for 14:00. The log is very verbose, especially the audio logging. I truncated nothing, and tried to add the log up until the sound has played.

[logcat_etar.txt](https://github.com/Etar-Group/Etar-Calendar/files/10910738/logcat_etar.txt)

In the above log you can see this behaviour at 14:00:01.127 to 14:01:17.007 (not truncated!). Do you have any idea what could be causing this? Battery optimizations are off for Etar. All notifications are enabled. Adaptive battery is on, but Etar is exempt. I'm specifically trying to make this work with adaptive battery on. Etar is also whitelisted in device_idle. App sleep has been disabled. I already disabled EasyMute, which was postponing notifications.

**Comment by Cwpute** [comment]
Hi, this seems to be a reccuring issue with calendars. Have you tried chaging the app's energy saving settings ? see here: https://www.maketecheasier.com/fix-delay-notification-android/

**Comment by sebaFlame** [comment]
Thank you, but I already tried all of those suggestions.
