### ISSUE TITLE
Support iCal feeds

### ISSUE THREAD

**Issue by SeerLite** [Etar-Group/Etar-Calendar#1365]
Some calendar programs allow using an ical file download link as a "feed". The calendar program periodically downloads the ical file and imports it.

Would this be possible to implement in Etar-Calendar?

Thank you!

**Comment by SeerLite** [comment]
Hi! No, it's not webcal/caldav. It's a very simple system where a server provides a literal download link for an ics file, and I can copy that link into my calendar program.
The calendar program then fetches that link periodically.

**Comment by jspricke** [comment]
Try https://f-droid.org/de/packages/at.bitfire.icsdroid/

**Comment by SeerLite** [comment]
Thank you so much! That's exactly what I needed!
