### ISSUE TITLE
new event and schedule reminder

### ISSUE THREAD

**Issue by Xaleborgia** [Etar-Group/Etar-Calendar#1366]
When I create a new event (on android 12), by default, there is a schedule reminder. But, by default, I dont want a schedule reminder. Is that possible ?

**Comment by bjlockie** [comment]
I haven't tried it. :-)
The 3 vertical lines in the top left.
Settings
General settings
Default reminder time
Set to 0 minutes.

**Comment by Xaleborgia** [comment]
it's too easy :) There is no 0, there is -1Min or +1min and above. But there is no 0 :(

**Comment by bjlockie** [comment]
-1 doesn't have any reminder
I tried it
0 has a reminder at 0 minutes which is not what you want anyways.

**Comment by Xaleborgia** [comment]
Oh yes thank you. I hadn't tried ☺️ I thought it was an alert before the start time. Thanks.
