### ISSUE TITLE
Disable alarm/notification

### ISSUE THREAD

**Issue by RobertCailliau** [Etar-Group/Etar-Calendar#1399]
For new events: I can set the alarm from -1 miute to 4 weeks, but I cannot set NO alarm.
Hence when I synchronise with our home server, my wife's computer rings, even for my prvate events.
This is a user interface bug (or I have not found out where to set default alrms to NONE.)

**Comment by jspricke** [comment]
There is an `X` to remove the reminder at the top right of the section.
