### ISSUE TITLE
Change calendar

### ISSUE THREAD

**Issue by RobertCailliau** [Etar-Group/Etar-Calendar#1400]
Once I have entered an event, it is impossible to change the calendar it belongs to.  I can change everything else but not the calendar.

**Comment by hcgrove** [comment]
That has been reported multiple times, the earliest one I've found is #62 

@rparkins999 says in #1266 that he has code for it, so it might be in a future version.

**Comment by GEkuL** [comment]
@RobertCailliau 
Please, close the issue, since it's a duplicate

**Comment by RobertCailliau** [comment]
Done (I think, user interface...)
