### ISSUE TITLE
fails to build due to missing android-test

### ISSUE THREAD

**Issue by lmamane** [Etar-Group/Etar-Calendar#1407]
`./gradlew build` fails for me with
```
/path/to/Etar-Calendar/app/src/test/java/com/android/calendar/widget/CalendarAppWidgetServiceTest.java:27: error: package android.test does not exist
import android.test.AndroidTestCase;
```
for me. I couldn't figure out how to declare the need for android.test in Gradle, nor how to tell gradle not to build that directory, so I just deleted it and then all builds fine (after GH-1406 in addition).

I figure you'll have a better solution than that :)

**Comment by lmamane** [comment]
I installed Debian packages:
```
google-android-build-tools-30.0.3-installer
google-android-platform-31-installer
google-android-platform-33-installer
```
(which automatically download the Google Android SDKs and put them in relevant subdirectories of /usr/lib/android-sdk)
and I build with `ANDROID_HOME=/usr/lib/android-sdk`

My understanding is that gradle and any dependencies are (supposed to be) automatically downloaded by the gradlew shell script, and by gradle itself?

**Comment by jspricke** [comment]
Can you try with
```
sudo apt install google-android-platform-tools-installer
ANDROID_HOME=/usr/lib/android-sdk ./gradlew :app:assembleDebug
```
As noted in the Readme: https://github.com/Etar-Group/Etar-Calendar#build-instructions
(Currently I get a HTTP error from gradle/jcenter so can't test myself)

**Comment by lmamane** [comment]
> ```
> ANDROID_HOME=/usr/lib/android-sdk ./gradlew :app:assembleDebug
> ```
 
Indeed, using :app:assembleDebug instead of the more usual/standard "build" task works for me, too.
