### ISSUE TITLE
Single digit dates are left aligned, should be to the right at the apps screen

### ISSUE THREAD

**Issue by sestarus13** [Etar-Group/Etar-Calendar#1415]
On pixel 4 with Lineage 20.0 the number for the date is aligned to the left instead to the right at the apps screen

**Comment by mkujer** [comment]
Yes, with the latest lineageos build. For my Samsung A52s. I have the same visual bug. [Here](https://ibb.co/vq04zp3) is a screen capture of the bug.

**Comment by jspricke** [comment]
This is not a bug in Etar but in the patched Lineage calendar. See https://github.com/Etar-Group/Etar-Calendar/issues/508#issuecomment-1525087543
