### ISSUE TITLE
Many errors on Android 13, sync w DAVx⁵

### ISSUE THREAD

**Issue by AeOeAa** [Etar-Group/Etar-Calendar#1420]
Hi,

I get so many errors, and have been for weeks, I don't know where to begin.
Is it working flawlessly for others?

When it syncs after changes (new, edit, delete), most views fail to show events - at all. They're synced alright, seen from other calendar apps.
Some times, they come back in Etar, sometimes I have to reset.

I'd love to help with these errors, but if it's just my setup that doesn't work, I'll rather use the time on something else and just use a different but way less smooth app.

Best regards, 
Martin

**Comment by jspricke** [comment]
Hi Martin,

sorry to hear. I use Etar on Android 13 (CalyxOS) With Davx5 without problems. Can you share some logcat logs to get any idea what's going on?

**Comment by AeOeAa** [comment]
There was an update and it fixed it.

**Comment by AeOeAa** [comment]
Closed
