### ISSUE TITLE
Allow to select UTC as timezone for events

### ISSUE THREAD

**Issue by dboehmer** [Etar-Group/Etar-Calendar#1466]
I have a calendar event for the release of the curl security fix on October 11 and wanted to add the time of day which was announced as around 06:00 UTC. Unfortunately I can’t select UTC. I tried to type:

* UTC
* universal
* coordinated

No results were found. Can you please add an entry for UTC to this list?

I am using Etar 1.0.36 from F-Droid on GrapheneOS.

![signal-2023-10-05-115207_002](https://github.com/Etar-Group/Etar-Calendar/assets/116007/c03eb34f-7e5e-4e4b-ae3b-a7f8c425aae2)

**Comment by landry314** [comment]
i cant search for any time zone at all

**Comment by razorloves** [comment]
> i cant search for any time zone at all. seems like the feature is broken.
> 
> i am using lineageos 20.0 built in version 1.0.36 on newest weekly update. pixel 5.

fixed. https://review.lineageos.org/370189

**Comment by hhartzer** [comment]
I'm also interested in this feature.

**Comment by landry314** [comment]
it was fixed. this should be closed.
