### ISSUE TITLE
Events created in Etar not synced with Google Calendar

### ISSUE THREAD

**Issue by jmevel** [Etar-Group/Etar-Calendar#1495]
Hi,

So, I've been using Etar for a long while and now that I want to switch to a new phone I just realized all the events I created in Etar aren't synced with my Google Calendar. They don't even show up on Google Calendar on the same phone. 

My Google account is connected in Etar, the `Synchronize this calendar` setting is activated and I do have this account showing up in Google Calendar as well.

What's the problem here? I have dozens of upcoming events in the following months with notes and addresses added, I don't want to recreate them all by hand on my new phone. It would completely defeat the purpose of having a calendar app like Etar linked to my Google account.

My phone is running on Android 10 BTW

<img src="https://github.com/Etar-Group/Etar-Calendar/assets/2572775/7da39358-510d-4507-9e2f-db12efd0a196" width="360" height="760">
<img src="https://github.com/Etar-Group/Etar-Calendar/assets/2572775/c575b066-b9fa-4657-a6b7-5f82bde47235" width="360" height="760">
<img src="https://github.com/Etar-Group/Etar-Calendar/assets/2572775/60505fcf-8d69-474a-9232-161e601a687a" width="360" height="760">
<img src="https://github.com/Etar-Group/Etar-Calendar/assets/2572775/e0f15be0-78b2-4836-99ff-f3c43ee633c1" width="360" height="760">

Thanks for your answers

**Comment by Haisha10** [comment]
@jmevel Is the automatic sync for your Google account enabled on your Android?

Also can you provide more information about your device?

**Comment by strk** [comment]
I would reopen this as I'm having that problem now, with latest Etar from f-droid.
I cannot "manually sync" because in the Android Accounts -> Google account preference I don't see a calendar. Could it be because I removed the google calendar app ? Does Etar sync depend on that ?

**Comment by strk** [comment]
I confirm that enabling Google Calendar app makes the manual sync available. Annoying, given I switched to ETAR to not depend on Google, but at least I sorted that out
