### ISSUE TITLE
Enable automatic per-app language support

### ISSUE THREAD

**Issue by ploink** [Etar-Group/Etar-Calendar#1497]
This is a new feature for android 13+ that allows one to pick an app's language from system settings or app info. 
I find this very useful as I have the android system in English but prefer some apps like Etar in my native language.

Implementation is very easy:
https://developer.android.com/guide/topics/resources/app-languages#auto-localeconfig
I have tried it locally and it works.

**Comment by jspricke** [comment]
Could you send this as a pull request?

**Comment by ploink** [comment]
> Could you send this as a pull request?

Sorry no luck. It appears I was using my older fork. I just cloned the most recent code and Studio wont even sync the project. And I would need to read the manual on how to create a pull request. I am not a developer.

It is very simple:

```
$ echo "unqualifiedResLocale=en" > app/src/main/res/resources.properties
$ git add app/src/main/res/resources.properties
```

Then add this to the module-level build.gradle:

```
    android {
      androidResources {
        generateLocaleConfig true
      }
    }
```

I hope you or someone else can pick this up. Thanks.

**Comment by jspricke** [comment]
@ploink I have opened #1502 can you have a look?
