### ISSUE TITLE
Toolbar is scrollable

### ISSUE THREAD

**Issue by ddast** [Etar-Group/Etar-Calendar#150]
The toolbar can be scrolled upwards.  In the day and week view this creates an empty gray area at the bottom.  See the following screenshot:
![scrolled_toolbar](https://cloud.githubusercontent.com/assets/6775792/22310636/2dbe3a0e-e350-11e6-8604-c4619dc01d16.jpg)

It is even possible to scroll the toolbar upwards until it vanishes and in this case it's not possible to scroll down again.  I am not sure what the intended behavior is since the code looks like scrolling is activated explicitely.  I would prefer to simply disable the scrolling of the toolbar and can prepare a pull request if this is desired.

**Comment by jspricke** [comment]
Interesting, tried it on two phones, but wasn't able to reproduce it. Can you sand a pull request, maybe that gives a hint.

**Comment by languitar** [comment]
I can reproduce this on omnirom, android 6

**Comment by jspricke** [comment]
got it as well, +1 for a patch :).
