### ISSUE TITLE
Can not update app on F-Droid

### ISSUE THREAD

**Issue by SuperMeepBoy** [Etar-Group/Etar-Calendar#1568]
I recently had an error where I could not update my app. It says it is due to an "unknown error". I deleted my app to reinstall it again and it worked.

Now new updates are coming again and here I go again, I can not update the app and it is very inconvenient to delete and reinstall everytime.
 
I'm on LineageOS 20-20240109-NIGHTLY-fajita.
I do not remember the first versio, I could not updte (sorry...).

**Comment by jspricke** [comment]
Can you get a logcat of that?

**Comment by SuperMeepBoy** [comment]
I don't know what you mean but if you have a doc/tutorial, I will certainly find time to do it.

**Comment by jspricke** [comment]
https://f-droid.org/docs/Getting_logcat_messages_after_crash/

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
See https://gitlab.com/LineageOS/issues/android/-/issues/6224
