### ISSUE TITLE
Can't install from F-Droid

### ISSUE THREAD

**Issue by mgw2013** [Etar-Group/Etar-Calendar#1581]
The attempted to replace the system's built-in older version 34 with the latest  F-Droid version fails with unknown error.

Device is running on LineageOS derivative i. e. Android 14 with latest security patches.

Logcat entry:

`02-07 21:50:12.518 13668 21311 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/org.fdroid.fdroid/cache/apks/f-droid.org--1/ws.xsoh.etar_41.apk Binary XML file line #44`

**Comment by chirayudesai** [comment]
Can you grab the full logcat?

**Comment by mgw2013** [comment]
Sure - logcat is cleared before installation attempt. Will post tomorrow

**Comment by PanderMusubi** [comment]
Same for me on new device, no problem on older device.

**Comment by mgw2013** [comment]
@jspricke  This worked for me! Thank you!

https://github.com/Etar-Group/Etar-Calendar/issues/1438#issuecomment-1783056333

**Comment by PanderMusubi** [comment]
Pretty sure I have the same problem. Not in the situation at the moment to run adb / logcat. Will wait for a fix on F-Droid.

**Comment by mgw2013** [comment]
> Pretty sure I have the same problem. Not in the situation at the moment to run adb / logcat. Will wait for a fix on F-Droid.

I'm afraid, most probably there will be no fix. This is an issue related to LOS.

**Comment by jspricke** [comment]
Etar can't fix this but I heard that LOS wil. So closing.

**Comment by PanderMusubi** [comment]
Ah yes, this one https://gitlab.com/LineageOS/issues/android/-/issues/6224
