### ISSUE TITLE
Events coming from external sync (like davx5) always treated as invite

### ISSUE THREAD

**Issue by Windkracht8** [Etar-Group/Etar-Calendar#1608]
I am using davx5 to synchronise caldav (and carddav/tasks), all event that come in via davx5 show the response_container. These events always have an organiser set and no attendees. The line 2091 from updateResponse in EventInfoFragment, hides the response_container only if there is attendee data, but in these cases the attendee data is not there. Which should be handled the same as <= 1 attendee. So I propose to change the line from 
(!mCanModifyCalendar || (mHasAttendeeData && mIsOrganizer && mNumOfAttendees <= 1) || (mIsOrganizer && !mOwnerCanRespond))
to
(!mCanModifyCalendar || !mHasAttendeeData || (mIsOrganizer && mNumOfAttendees <= 1) || (mIsOrganizer && !mOwnerCanRespond))

**Comment by jspricke** [comment]
Hi @Windkracht8 can you please open a pull request with the proposed change?

**Comment by Windkracht8** [comment]
done: https://github.com/Etar-Group/Etar-Calendar/pull/1609
