### ISSUE TITLE
India Holidays are not repeated on the same date every Year

### ISSUE THREAD

**Issue by cookieninja01** [Etar-Group/Etar-Calendar#1610]
Hi. Thanks for your update v1.03 on F-Droid. The calendar has holidays which repeat annually on the same date. This is incorrect, as most holidays except three (Republic Day, 26 Jan; Independence Day, 15 Aug; and Mahatma Gandhi's Birthday 02 Oct), do not repeat on the same date every year. These holidays are based on the lunar calendar and occur on different dates each year
Pl refer to the official list of holidays available at www.india.gov.in/calendar/2024/export.ics, to see that other than the three that I have described above, all other holiday dates are incorrect. These dates do not repeat on the same date every year, so do no repeat these dates, but try to obtain fresh dates from https://www.india.gov.in/calendar?a=1699488000014, for each year. Thanks.

**Comment by jspricke** [comment]
Etar does not contain any pre defined holidays nor is there a version 1.03. I guess you mean a different software, so closing.
