### ISSUE TITLE
Integration of iCalendar feed (read-only) not working

### ISSUE THREAD

**Issue by notYetLost** [Etar-Group/Etar-Calendar#1611]
I tried to integrate some outbound calendar feed in iCalendar format hosted in Teamup.com.

However I cannot get this type of calendar feed to work in Etar.
The URL of the feed ends on ".ics".

Please support this type of calendar feeds, showing them in separate color denoting they are read-only.

**Comment by jspricke** [comment]
Etar does not do calendar sync, see https://github.com/Etar-Group/Etar-Calendar?tab=readme-ov-file#how-to-use-etar

**Comment by travisfw** [comment]
This is hard to accept. I don't want to "sync," I just want to view an ics accessible at a URL.

EG of the [San Francisco Recreation & Parks department](https://sfrecpark.org/Calendar.aspx?CID=35)

I would be happy to save the URL some other way and just browse it with Etar when I click through, necessarily interspersed with my own calendar that I am using Etar to manage, so I may copy events over one at a time.

**Comment by notYetLost** [comment]
What ever CalDAV feed you have, use DAVx5 to get it to your default calendar app.

Am 14. September 2024 18:42:02 MESZ schrieb Travis Well ***@***.***>:

**Comment by travisfw** [comment]
So you're saying that to view a single ics resource and copy an event over, I have to ① install another app (DAVx5), ② add the URL, ③ go back to Etar, ④ copy the event, and then ⑤ go back to DAVx5 and ⑥ remove the URL.

> What ever CalDAV feed you have, use DAVx5 to get it to your default calendar app.
