### ISSUE TITLE
add google agenda in etar offline 

### ISSUE THREAD

**Issue by JazzinTown** [Etar-Group/Etar-Calendar#1615]
Etar imported my google agenda but it is unclear to me if it is stored locally on my phone or still in the google cloud. 

Were does Etar store my agenda exactly ?

And is it possible to import the google agenda with its history as a locally stored agenda on my android phone ?
( i did also request a backup of my agenda history with google)

Hope to hear from you, Thank you !

**Comment by jspricke** [comment]
Etar does not handle data storage nor syncing, see https://github.com/Etar-Group/Etar-Calendar?tab=readme-ov-file#technical-explanation

**Comment by JazzinTown** [comment]
Where does Etar store my appointments and agenda events. How can I make a backup of it when it is a local agenda.

**Comment by jspricke** [comment]
As written above, Etar **has no data storage**. You can try backing up the calendar provider if you want.

**Comment by JazzinTown** [comment]
Thanks for the given information.
