### ISSUE TITLE
Double Notification Alerting Bug

### ISSUE THREAD

**Issue by Cyberes** [Etar-Group/Etar-Calendar#1684]
My events seem to notify twice and I feel two vibrations for each event. It seems that one is at the event reminder time (this is the default behavior) and one at the minute after that (this is the second alert that seems to be unintended).

I do not get two notifications, it's more like I get two alerts/vibrations at two different times for the same notification.

I tested notifications with Simple Calendar Pro and notifications worked as expected, meaning it's not something with my calendar events.

**Comment by da-the-dev** [comment]
Same here!

**Comment by Cyberes** [comment]
Pinging @jspricke @jonas-haeusler 

This bug is kind of a show stopper, can you please take a look at it?

**Comment by Cyberes** [comment]
hey, any update?

**Comment by Cyberes** [comment]
@Gitsaibot

**Comment by jspricke** [comment]
@Cyberes please stop pinging bugs. If you want this fixed, please send a patch with the fix. Note that Etar is developed by volunteers in their spare time that have other jobs to finance their live.
