### ISSUE TITLE
Attempt to modify recurring events "No calendar" associated inaccurately

### ISSUE THREAD

**Issue by sk425** [Etar-Group/Etar-Calendar#1688]
OS: GrapheneOS 
Build: 2024062000
Etar version: fdroid 1.0.46

Issue:
Upon editing any recurring event, the app declares "No calendars" and prompts me to create a calendar. There is already calendars attached to these events. 

The issue currently prevents any modifications.

**Comment by jonas-haeusler** [comment]
same issue as reported in https://github.com/Etar-Group/Etar-Calendar/issues/1686. feel free to try the provided patch and report back.

**Comment by sk425** [comment]
> same issue as reported in #1686. feel free to try the provided patch and report back.

The patched debug app works for me as intended.
