### ISSUE TITLE
Filter Calendar Event based on eventcolor 

### ISSUE THREAD

**Issue by rvishal1991** [Etar-Group/Etar-Calendar#170]
Hey Folks,

I 've tried to filter events using Etar library. I'm still bit confused from where its getting all the events and setting this all events array for every ViewType.

I come to know this is something related to AsyncService. But I am still figuring out can you tell me from where universal event array is shared between all the ViewType

**Comment by JayMehta97** [comment]
Even I have been facing this issue for my app. Searched the internet but could not find a proper solution. It would be great if anyone could solve this issue and post the solution or update the code in github. Thanks in advance!

**Comment by jspricke** [comment]
Android has a build in calendar provider: https://developer.android.com/guide/topics/providers/calendar-provider.html. Etar just displays and modifies this DB.

As this is not really an Etar issue, I will close this.
