### ISSUE TITLE
Share to function doesn't run

### ISSUE THREAD

**Issue by pin88888** [Etar-Group/Etar-Calendar#1722]
Hallo!
I have been used Etar for many years on my old smartphone (Android 10). Last week I installed it on the new telephone but here I cannot share events planned with it.
Nor is possible to save them to SD card.
If I try that, I get the message “Error. It was not possible to share the event” (my translation from German). From other apps, i.e. file manager, there is no problem on sharing files.

_Information about the new smartphone and Etar settings_
Android 11
Almost all google apps and services are de-installed or de-activated. Only the system apps and File Manager is now active.
Etar version 1.0.47
Etar has permissions to files and media,on Calendar and Contacts.

_Other strange behaviour noticed_:
Once Etar is started, it is not possible to close it, even using the system service “force closing”. At the top right corner of Etar widget there is the locked symbol. BTW, the same happens for the app FairEmail and F-Droid Dateimanager.

_What I have tried (but every time without success)_:
a) downgrade Etar to the previous version 1.0.46 (as on my old smartphone)
b) re activated the google app Calendar
c) re activated the google service app
d) moved the Etar app from SD card to the telephone memory.

Is this issue already known?
There is a workaround to get the share to and/or save to functions?

Many Thanks in advance for contributes

**Comment by jspricke** [comment]
> Hallo! I have been used Etar for many years on my old smartphone (Android 10). Last week I installed it on the new telephone but here I cannot share events planned with it. Nor is possible to save them to SD card. If I try that, I get the message “Error. It was not possible to share the event” (my translation from German). From other apps, i.e. file manager, there is no problem on sharing files.

I guess that's due to some configuration issue on your phone (maybe you de-activated too much?).

> _Other strange behaviour noticed_: Once Etar is started, it is not possible to close it, even using the system service “force closing”. At the top right corner of Etar widget there is the locked symbol. BTW, the same happens for the app FairEmail and F-Droid Dateimanager.

You can't really close apps in Android: https://developer.android.com/guide/components/activities/process-lifecycle

> Is this issue already known? There is a workaround to get the share to and/or save to functions?

Those are not issues in Etar, so closing here.
