### ISSUE TITLE
Notification order

### ISSUE THREAD

**Issue by user18x** [Etar-Group/Etar-Calendar#1735]
I want to know which order for notifications is right?

As example i want a notification 12h, 2h and 30 minutes **_before_ the event starts**:
1. 12h
2. 2h
3. 30 min

or
1. 30 min
2. 2h
3. 12h

Or isn't the order important?
1. 1 day
2. 2days
3. 10 min
4. 30 min
5. 12h
6. ...

**Comment by jspricke** [comment]
Just try it ;).

**Comment by user18x** [comment]
Wow, that's a help!

I hope if you need help in another section you will get this answer too!
