### ISSUE TITLE
Cannot turn 'one-time event' into a weekly event after creation

### ISSUE THREAD

**Issue by excited-bore** [Etar-Group/Etar-Calendar#1746]
If you've created an entry for as a 'one-time event' and later change mind to wanting it occur every week, you're unable to.
Only upon initial creation are you able to change that setting apparently.

**Comment by jspricke** [comment]
It works for me, select an event, press the pencil to edit it, press on "One-time event", enable the repeat on top right.

**Comment by excited-bore** [comment]
Im sorry for reopening this issue, but it appears that it only doesn't work when there's already a weekly event on the same hoursschedule.

A popup alerting the user that is the case / asking for a double booking would be nice.

**Comment by jspricke** [comment]
> Im sorry for reopening this issue, but it appears that it only doesn't work when there's _already a weekly event on the same hours+day_.

I can't reproduce that either.

**Comment by excited-bore** [comment]
Well this is very weird. I mean there was this one day/hour span that just *did not* allow to press the button "one-time event" bttn when editing, but when i deleted it and recreated the appointment and it just worked..

There was nothing special about the event, no special characters in the titel apart from capital case letters  and `-`, otherwise everything was left default. And a double booking with the following weekday (but again, after deletion it worked nicely like before).
 
In the end of the day it isn't really appbreaking bug either way. So sorry for reopening this issue for nothing
