### ISSUE TITLE
How to sync Etar and MS Exchange

### ISSUE THREAD

**Issue by Stefan-etar** [Etar-Group/Etar-Calendar#1757]
Hello,
I am already using Etar with a Nextcloud/Caldav-Calender. Now I want to add an MS Exchange-Calender. The description of Etar says that’s possible but I can’t find a way to do so.
Can anybody help me with this question?

**Comment by jspricke** [comment]
The description is a bit missleading here, Etar does not sync calendars itself but you need an other app to do that, see https://github.com/Etar-Group/Etar-Calendar?tab=readme-ov-file#how-to-use-etar
