### ISSUE TITLE
Supercharge "Schedule" functionality 

### ISSUE THREAD

**Issue by nielstron** [Etar-Group/Etar-Calendar#1802]
I noticed that Etar suggests to "Schedule" an event in the calendar when highlighting a date in text. I have now for a longer time been successfully using a small side project of mine, [Text2Calendar](https://github.com/ApiInnovators/text_to_calendar), that extracts more complex contexts, relative time, suggests a title of the event etc. 

If there is any interest in integrating or collaboration from your side I would be glad to find a way to combine our efforts.

**Comment by jspricke** [comment]
Hi Niels,

that's an interesting project but Etar is a free software project so we don't accept code that needs an API key, or relies on closed source code such as OpenAI or android.gms.
