### ISSUE TITLE
Dark widget setting 

### ISSUE THREAD

**Issue by Tonus1** [Etar-Group/Etar-Calendar#190]
Hi, 
Would be perfect to add a dark widget. 
Regards

**Comment by PanderMusubi** [comment]
For users to have complete and independent control over light/dark theme for the app and the widget, simply add a seperate setting for the widget theme.

**Comment by PanderMusubi** [comment]
See also https://github.com/Etar-Group/Etar-Calendar/issues/174

**Comment by Tonus1** [comment]
Isn't that done ?

**Comment by frknltrk** [comment]
i'm still looking forward for this feature.
