### ISSUE TITLE
How to add a calendar?

### ISSUE THREAD

**Issue by keunes** [Etar-Group/Etar-Calendar#196]
Maybe I missed something, but how do I add a calendar?
I just installed the app and all calendars that I have in Google's calendar appear as well, but I don't see a button to add a new local or remote calendar.
I would expect an 'add' button next to 'calendars to sync' in the calendars view...

**Comment by jspricke** [comment]
Etar is only there to view and edit existing calendars. If you want to add new once, Android has the concept of adapters and accounts. So for a local calendar, you can use [Offline Calendar](https://f-droid.org/repository/browse/?fdfilter=calendar&fdid=org.sufficientlysecure.localcalendar) and  for a remote CalDAV there is [DAVdroid](https://f-droid.org/repository/browse/?fdfilter=davdroid&fdid=at.bitfire.davdroid) for example.

**Comment by keunes** [comment]
Ok. So I've added my nextcloud's Calendar in DAVdroid and synced it in DAVdroid as well. In DAVdroid the two calendars show up that I've created in Nextcloud, but nothing appears in Etar. What's going wrong?

**Comment by keunes** [comment]
Just installed to check, and Offline Calendar does work (newly created test calendar pops up in Etar's list immediately), DAVdroid doesn't.
DAVdroid 1.5.0.2-ose (via F-Droid)
Etar 1.0.10 (also F-Droid)
Offline Calendar 1.8 (same...)
 on Fairphone 2 (Android 5.1)

**Comment by jspricke** [comment]
I have the same setup working over here. Can you make sure the calendars are synced in DAVDroid? Check in Options -> Accounts -> DAVDroid. Check that the calendar is synced and that all of them are shown in manage account. Also have a look in the Etar options calendar to display and to synchronize that they show up there.

**Comment by keunes** [comment]
There is no section 'DAVdroid' in Etar, so not sure what you're referring to...
What I do have in Etar: Settings -> mail@xxx.nl -> 'No calendars'
What I have in DAVdroid: mail@xxx.nl -> 'CardDAV' and 'CalDAV' where all calendars are synced. Also a newly created calendar in DAVdroid doesn't show up in Etar (though the related account does).

If I can do anything to help debug, please let me know...

**Comment by jspricke** [comment]
OK, looking all good so far. Can you try to get a logcat from when Etar is starting? Also, clearing the data of Etar in Android setting -> apps -> Etar could help (shouldn't delete any relevant data).

**Comment by keunes** [comment]
> Etar in Android setting -> apps -> Etar could help

Done. Didn't help :/

> Can you try to get a logcat from when Etar is starting?

Was a bit of a hassle, but I got it working. Now have a 5.266-line long logcat: 
[logcat-etar.txt](https://github.com/Etar-Group/Etar-Calendar/files/926708/logcat-etar.txt)
Hope there's no too sensitive data in there :P

**Comment by jspricke** [comment]
Nothing interesting on first sight. I hope to have my Fairphone back by tomorrow, so I should be able to reproduce it bit by bit. (maybe you can get me an account on your nextcloud?) Could you mail me privately, maybe (address is on my github page)?

**Comment by keunes** [comment]
> I hope to have my Fairphone back by tomorrow, so I should be able to reproduce it bit by bit.

👍

> Could you mail me privately, maybe

Will do.

**Comment by keunes** [comment]
Solved with a software upgrade (Android 5 -> 6)
