### ISSUE TITLE
What is the Dependency for this library?

### ISSUE THREAD

**Issue by chnouman** [Etar-Group/Etar-Calendar#219]
i need to know what is the dependency for this library please guide me.

**Comment by jspricke** [comment]
Etar is an Android app not a library and you can find it's dependencies and build process in the readme: https://github.com/Etar-Group/Etar-Calendar/blob/master/README.md. Also, this is an issue tracker, not a help channel, so closing.

**Comment by chnouman** [comment]
i'm really sorry dear but actually i don't find a way to use this from README.md.

**Comment by jspricke** [comment]
"use" as in how to use Etar on an Android phone or "use" as in how to compile it?

**Comment by chnouman** [comment]
how to compile it dear.

**Comment by jspricke** [comment]
https://github.com/Etar-Group/Etar-Calendar/blob/master/README.md#build-instructions

**Comment by chnouman** [comment]
ok
