### ISSUE TITLE
Feature Request: Reduce portion of night hours & making text smaller (Week)

### ISSUE THREAD

**Issue by Scythens** [Etar-Group/Etar-Calendar#226]
- **Ability to reduce the size of hours X to Y in the week calender**
I always use the week-type calendar. As I obviously have most of my appointments between 9AM and 7PM, I sometimes wish to see these hours easier. I'd love an option in the settings that reduces the "block-size" of certain hours (e.g. midnight to 6AM) to the space of one or two blocks, instead of six blocks. Optionally adding a bold line between the timespan that has been reduced in size and the regular hours would be great.

- **Ability to reduce font size of event names in the week calender**
Another option that would be very beneficial is reducing the text size of event names in the week-type calendar. My eyes aren't that bad and although the current font size is not huge at all, I could easily read it if it'd be two sizes smaller, leaving more space for more letters of the event name.

Love the app <3

**Comment by smichel17** [comment]
> Ability to reduce the size of hours X to Y in the week calender

This could be done dynamically without a setting.

- On weeks/days where no events are showing, just display everything as-is.
- In the daily view, on days with events, if there is an X hour period with no events, collapse the middle X-4 hours into a single dark line.
    - Add in a few safety rules to avoid excessive collapsing.
    - Tapping the line expands back to the normal view.
- In the weekly view, follow the same rules as above except those hours must not have events on any of the visible days.


Before I go ahead and add my +1, though, I do wonder if this somewhat complex feature is really necessary.

I'm guessing you want this feature for the same reason I do: it's frustrating to switch to daily/weekly view and have some or all your events be off screen. How much of the frustration would be solved if Etar were smarter about selecting the default scroll position and zoom when the day/week view is selected?

**Comment by Scythens** [comment]
Late response, busy days.

> This could be done dynamically without a setting

I have little to no knowledge of application development or programming, but wouldn't this mess with dynamic timezones for frequent flyers or when you have a single event at 4AM in the week (assuming you're using the week calender with seven days displayed)?

> How much of this would be solved by #205?

Everything. I would love this, especially since I only have a handful of appointments every day for not even every day of the week.

**Comment by aidam38** [comment]
I don't know how much there is point in reviving this issue, but I would really appreciate the ability to make the font smaller. Right now I can't even have an event called School without the line wrapping.

**Comment by MurphySunset** [comment]
And that's my turn to ask for this feature ! It is really annoying not to be able to see the content of 2 concurrent events. @jspricke @xsoh ?

**Comment by jspricke** [comment]
@MurphySunset feel free to open a pull request with the implementation :).
(please don't ping people otherwise)

**Comment by MurphySunset** [comment]
Sorry!

**Comment by jspricke** [comment]
done in master
