### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by sushantrijal** [Etar-Group/Etar-Calendar#238]
How to use the library it is giving
Error:Cannot read packageName from /home/innu008/Downloads/Etar-Calendar-master/external/calendar/AndroidManifest.xml
Can tell me what is the problem , I have done many things as referred in your library.
Thanks

**Comment by jspricke** [comment]
You probably forgot to initialize the git submodules, see: https://github.com/Etar-Group/Etar-Calendar#build-instructions. Apart from that, this is an issue tracker, not a support forum.
