### ISSUE TITLE
Cannot run Etar from f-droid the first time

### ISSUE THREAD

**Issue by Fabiensk** [Etar-Group/Etar-Calendar#249]
**Scenario**:
- Install Etar from f-droid applications manager
- Launch Etar from f-droid.
- You are asked in a pop-up to give calendar access (click yes)

**Actual result**:
- A "_screen overlay detected_" pop-up dialog is displayed, asking me to give Etar such a rights. Click on the button of the pop-up.
- You are redirected to the Android "_draw over other apps_" system settings screen but there cannot change the overlay right for Etar
- Leave the settings. Etar is not launched.

**Expected result**:
After having accepted to given the app access to the user calendar, Etar should be fully started.

**Alternative scenario**:
Like the original scenario, but by launching Etar from the Android applications list.

**Additional notes**:
It did not happen all the times when I repeated this scenario (must most of the times). Going in the Android application management and giving the Calendar, Contacts and Storage rights solved the issue. In some other attempts, trying to run the app several times (from the application list) sometimes succeeded (rights were properly added after being prompted). 

Device: Samsung Galaxy S5 mini, Android 6.0.1
Etar version: 1.0.12 (f-droid)

**Comment by smichel17** [comment]
Pretty sure this is not an issue with Etar. Are you running an app that uses an overlay? For example, (shameless plug) [Red Moon](https://github.com/raatmarien/red-moon). You need to turn off that app (or whatever feature of it uses an overlay) before you can grant permissions to any app, or your phone will behave as described.

**Comment by smichel17** [comment]
Pretty sure this is not an issue with Etar. Are you running an app that uses an overlay? For example, (shameless plug) [Red Moon](https://github.com/raatmarien/red-moon). You need to turn off that app (or whatever feature of it uses an overlay) before you can grant permissions to any app, or your phone will behave as described.

**Comment by jspricke** [comment]
It is actually a Etar problem, as there is code to display a notification why we need the calendar right.
If no one has an idea how to give this information without an overlay, we could fix it. Otherwise I would propose to simply remove the notification.

**Comment by smichel17** [comment]
The notification in question is the one to grant calendar permissions. You can't remove it if you want calendar permissions.

**Comment by Fabiensk** [comment]
Typical attempt:
* I just installed Etar. I press in f-droid the launch button (« Lancer » in French). I get the pop-up asking me to give access to the calendar. I press OK.
![f-droid 1](https://user-images.githubusercontent.com/378842/29747733-10c759b0-8b04-11e7-96e4-658209489c26.png)

* Then I get the overlay warning pop-up. I press « Open the settings ».
![f-droid 2](https://user-images.githubusercontent.com/378842/29747735-1bcdf710-8b04-11e7-9785-8c179e597c9a.png)

* In the settings, I cannot allow Etar to use overlay. The only thing I can do in going back to f-droid.
![f-droid 3](https://user-images.githubusercontent.com/378842/29747738-24ba4f2c-8b04-11e7-9183-d0d5e30b0168.png)

* Sometimes, after one or several attempts to launch Etar from f-droid, it actually run and I am asked to give access to the storage. If I accept, then I can use Etar.
![f-droid 4](https://user-images.githubusercontent.com/378842/29747739-27a56686-8b04-11e7-8a7f-f42fd491558b.png)

I don't know much about Android development, but I suppose that Android is confused because the Etar UI is not launched yet and the access pop-up is displayed over another application. Maybe (only a theory) if it was possible to display Etar then get the permission pop-up it could solve the issue.

**Comment by jspricke** [comment]
Thanks for the screenshots, as I wrote it's an Etar problem. The code is here:

https://github.com/Etar-Group/Etar-Calendar/blob/604137054676c359bf94b1d656ffbd3fd314aa8a/src/com/android/calendar/AllInOneActivity.java#L430

We will probably remove it in the next version.

**Comment by smichel17** [comment]
@Fabiensk can you clarify what the bug is by adding an **expected result** to compare with the **actual result**?

I interpreted the problem to be one thing, but @jspricke seems to have interpreted it differently, base on the proposed solution. So, I'm not sure any more what the actual bug is, or whether the proposed solution will solve it. I think it's a good idea to figure that out before we make changes :)

**Comment by jspricke** [comment]
No, I only proposed to remove the overlay, namely "Etar requires calendar read and write permissions to work properly. Please try again." But I didn't find time to try this, sorry.
