### ISSUE TITLE
Changing days per week should update current week view

### ISSUE THREAD

**Issue by KeronCyst** [Etar-Group/Etar-Calendar#261]
This would be very helpful in certain consecutive days when we've got just a ton of events in overlapping hours going on!

**Comment by jspricke** [comment]
You can change they days per week in settings, does that help you?

**Comment by KeronCyst** [comment]
Oh, I forgot about that feature. You're right. Here is an unrelated, new issue now: after picking a different number, and then returning to the Week pane, it is still on the old number of days. You have to manually pick a different interval and then return to Week for the new number of days to take effect.

**Comment by ankitguptaiphone** [comment]
@jspricke   after picking a different number of days from setting it is still showing the old view days , how we solved this  issue any advice ?
