### ISSUE TITLE
Feature Request: Month Widget

### ISSUE THREAD

**Issue by realmain** [Etar-Group/Etar-Calendar#264]
It would be nice if there was a month widget, similar to google calendar :)

Thanks

**Comment by smichel17** [comment]
Personally I would rather if some other app handled widgets (even if it is developed by the same group of people working on Etar). This allows people to mix and match apps for the functionality they want,  without any bloat. It's the beauty of using the shared calendar provider.

**Comment by jspricke** [comment]
Same as #162. Also, please provide code if you want it.
