### ISSUE TITLE
Show content of "assets" folder on fdroid

### ISSUE THREAD

**Issue by mueller-ma** [Etar-Group/Etar-Calendar#270]
When providing metadata via a fastlane directory, fdroid automaticly shows them in the store. Do you think it's possible to convert the current assets folder or use symlinks to provide a fastlane or Gradle Play Publisher like directory structure?

Example: https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android/en-US
Info:
- https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/#directly-in-the-f-droid-repo
- https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots

**Comment by jspricke** [comment]
Sorry, totally forgot to answer here. I would even propose to move the files into the new structure. Would be great if you could send a patch for it.

**Comment by mueller-ma** [comment]
I can work on it, but I would start to copy files, because I don't know what to do with e.g. zone.tab.

**Comment by jspricke** [comment]
Sorry for not responding earlier. Moving everything in assets/_pre_prod/ should be fine.
