### ISSUE TITLE
Show correctly STATUS:CANCELLED event

### ISSUE THREAD

**Issue by Spheerys** [Etar-Group/Etar-Calendar#278]
Hi,

I have the use of the Canceled status for some events on a distant .ics file
The code on the event is : 
```
STATUS:CANCELLED
```
But Etar don't show these events differently than the normal ones.

Could it be possible to show the canceled events striped and eventually lighten ?

**Comment by Spheerys** [comment]
Up to my 2 years old proposition !
I saw there was several issues openned on the same idea :
https://github.com/Etar-Group/Etar-Calendar/issues/71
https://github.com/pimutils/khal/issues/587

Any chance to see this nice improvement implemented ?

**Comment by Spheerys** [comment]
Pleaaaase :)

**Comment by Kalytis** [comment]
Couldn't agree more, it would be nice to edit, or at least show, the status of events. Better integration with Thunderbird !!

**Comment by MathieuSchopfer** [comment]
That would be nice to have.

Calendar Contract expect a `STATUS` column with three possible states: `TENTATIVE`, `CONFIRMED`, and `CANCELED`.

But how should this interact with status-dependent formatting properties (e.g. attendance status) ?

**Comment by MathieuSchopfer** [comment]
I think we can close this issue.
