### ISSUE TITLE
possible for an event box to span multiple days?

### ISSUE THREAD

**Issue by iad24** [Etar-Group/Etar-Calendar#279]

**Comment by jspricke** [comment]
Can you please give a more detailed error description?

**Comment by iad24** [comment]
Like how Google Calendar do it.
Like the Dec 26 to 29 event below

![img_20171208_175819 599 png](https://user-images.githubusercontent.com/15226261/33760700-82a45ae0-dc41-11e7-9d9b-1d0cdd2e82ad.jpeg)

**Comment by jspricke** [comment]
Duplicate of #5.
