### ISSUE TITLE
Error:(141, 5) error: invalid resource type 'attr' for parent of style.

### ISSUE THREAD

**Issue by iad24** [Etar-Group/Etar-Calendar#280]
After I clone. Then do:
git submodule init
git submodule update

Then open in Android Studio 3.0
Then got this:
![screen shot 2017-12-08 at 12 05 06 pm](https://user-images.githubusercontent.com/15226261/33750648-602f6008-dc10-11e7-89cc-e87752f646f6.png)

**Comment by ankitguptaiphone** [comment]
go to project structure  and change  the compile tool version and build tool version to 26 maybe  this  solution  help you   , check the screenshot 
![screen shot 2017-12-10 at 10 47 01 pm](https://user-images.githubusercontent.com/1904874/33807376-13516a68-ddfc-11e7-881c-57d44dd06d4c.png)
