### ISSUE TITLE
About View

### ISSUE THREAD

**Issue by ramack** [Etar-Group/Etar-Calendar#284]
Currently the "About" just gives the Build-Version and is reachable via "Settings" - where I did not really expect it. Wouldn't it be wise to move it one level higher directly to the navigation view and also add information about where to report issues, the projects website, Authors (yes - they earn credit, thanks for the good work!), license of the app and maybe the used libraries?

Talking about license: I suggest to add a file LICENSE in the repository root with the full licensing.

**Comment by jspricke** [comment]
This is discussed in #222 already. Reporting issues was added in #19 already. I don't care so much for the other information ;). The license is already mentioned in every source file, which should be enough.
