### ISSUE TITLE
Could the code of this project be compiled by Android Studio?

### ISSUE THREAD

**Issue by nicejerry** [Etar-Group/Etar-Calendar#286]
This project is really excellent for keeping updating.
I do want to learn more.
However I couldn't open this project by Android Studio. Is it developed by Android Studio?

**Comment by jspricke** [comment]
I guess you are missing this:
https://github.com/Etar-Group/Etar-Calendar#build-instructions

Also, please give a detailed error description next time.

Closing as not a bug.
