### ISSUE TITLE
Project setup - build error

### ISSUE THREAD

**Issue by WerVbn** [Etar-Group/Etar-Calendar#292]
I can't build or setup a new Etar-Calendar project with android studio version 3.0.1.

After
`git clone --recursive git://github.com/Etar-Group/Etar-Calendar.git`

i opened the Etar-Calendar with android studio. The gradle console shows the following errors:

1. error:

`AGPBI: {"kind":"error","text":"error: invalid resource type \u0027attr\u0027 for parent of style.","sources":[{"file":Etar-Calendar/external/chips/build/intermediates/bundles/debug/res/values/values.xml","position":{"startLine":140,"startColumn":4,"startOffset":8332,"endLine":150,"endColumn":12,"endOffset":9070}}],"original":"","tool":"AAPT"}
Etar-Calendar/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:3070: error: invalid resource type 'attr' for parent of style.'`

2. error:
```

Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
```

How can I fix theses errors in order to build the project correctly? The proposed solution in #280 didn't work for me.

**Comment by DilbagSandhu** [comment]
In 'Project' view open:
1. Etar-Calendar> external> chips> res> values> styles.xml
2. find the style "RecipientEditTextViewBase" and change its parent to "android:Widget.Material.AutoCompleteTextView" 
3. rebuild the project. :)

**Comment by jspricke** [comment]
I wasn't able to reproduce this with the latest master. Can you please try again and either close or send a pull request? Thanks!

**Comment by devoma** [comment]
I have imported this project to Android Studio. [Try it](https://github.com/devoma/EtarCalendarSample)

**Comment by inigomurgui** [comment]
I also import the project with android studio version 3.0.1, import all the external projects (datetimepicker, ex and timezonepicker manullay), build at the end everything ok, but then with a nexus API 25 emulator the application does not start. Moreover, I try it on an Elephone with Android 5.1 API 22 and when I click on the app icon it closes inmediately. 
Apart from that, I also try devoma example with the same result...
Where can be the problem? Any suggestions?

**Comment by jspricke** [comment]
@inigomurgui that's a different problem, could open a new issue for that?

**Comment by ramsonline** [comment]
i just checked out the latest master and it worked without any troubles... (Android Studio 3.0.1)
