### ISSUE TITLE
Unable to fetch submodule path

### ISSUE THREAD

**Issue by lokhandeyogesh7** [Etar-Group/Etar-Calendar#297]
I am not able to fetch some of the submodules getting following error

Fetched in submodule path 'external/datetimepicker', but it did not contain 98dd                                 a20d2fab99ac1c0b0fc92259f9274415cf47. Direct fetching of that commit failed.

**Comment by lokhandeyogesh7** [comment]
Solved this by using 
git submodule init
git submodule sync
git submodule foreach "(git checkout master; git pull)"

marking it as closed

**Comment by tophernuts** [comment]
I was getting this error to and this fixed it!

Could this be added to the [build instructions](https://github.com/Etar-Group/Etar-Calendar#build-instructions)

**Comment by jspricke** [comment]
This is a wrong pointer in our submodules, will be fixed soon, sorry.
