### ISSUE TITLE
Add option to change primary color

### ISSUE THREAD

**Issue by gsantner** [Etar-Group/Etar-Calendar#310]
The teal/turquise looks quite bright. It would be great to have an settings option to set a custom color.

Note that dark overall theme is not the target of this.

**Comment by kaoneko** [comment]
I second this, albeit for different reasons. I've never liked the teal and I've gone so far as to see if I could change some values in the source and compile Etar myself, but I didn't succeed in that as I'm not very knowledgeable regarding these things.

Would love to be able to change the main color through the settings screen!

**Comment by TheoRet** [comment]
I would also like to change the primary color. I really dislike the turquoise.
Apart from that, the optics and design of this calendar app is great!
