### ISSUE TITLE
Widget Dark Theme

### ISSUE THREAD

**Issue by GiiantWaffle** [Etar-Group/Etar-Calendar#329]
Nice Calendar!  Thanks!

WIDGET: Dark Theme???

**Comment by charlescrammond** [comment]
+1
Love the Calender widget, please in dark without the black border, so its seamless. Warm thoughts.

**Comment by jancborchardt** [comment]
This is a duplicate of issue #190. @GiiantWaffle could you close this? Then let's continue there. :)
