### ISSUE TITLE
Why do I have to sign in to use this calendar? 

### ISSUE THREAD

**Issue by aFoxWhoIsNice** [Etar-Group/Etar-Calendar#335]
Hi I really like Etar, but one thing I don't understand is why it requires me to sign into an email account to organise my day. It only accepts my Google account, and doesn't work with my free ProtonMail & Tutanota account. This really takes away the entire point of not using Google Calendar and keeping it from snooping in my life. Please give us the option to not sign in, and be able to add calendar events.
Thank You.

**Comment by ramack** [comment]
I am using Etar with my self-hosted DAV server and an own email-address. So it definitly works without google. What is exactly the problem on your side? Can you try to explain what you exactly did and what you configured where? Maybe with a screenshot of the error message you get?

**Comment by aFoxWhoIsNice** [comment]
After switching off sync for those Google accounts, here's the message I get when I try to add an event. https://imgur.com/jHpT6Qo

**Comment by ramack** [comment]
You need a Calendar... Often there is a device local calendar available on Android (I guess it is coming with the native Calendar App) that is not synched to the cloud. If you don't have one either create one somewhere in the cloud and sync it E.g with DAVdroid or you might try one od the apps providing a local Calendar for example 'Offline Calendar'

**Comment by aFoxWhoIsNice** [comment]
I downloaded offline calendar Offline Calendar (Offline calendar adapter) - https://f-droid.org/app/org.sufficientlysecure.localcalendar can't figure out how to make it work though. Also, default calendar is Google's. Help please.

**Comment by ramack** [comment]
What do you see if you go to "Shown Calendars" (or how it is named in English - the menu entry above "settings") after tipping the sandwich icon (or swiping in from the left side)?

There you should see all the calendars that are provided by the apps on your device. If you create a new local calendar with "Offline Calendar" it should be visible there, beside your google calendar. If you don't want to see your g-calendar at all in Etar, just uncheck it there.

**Comment by aFoxWhoIsNice** [comment]
Done, thanks.

**Comment by ramack** [comment]
Good. So if it is solved, can you close the ticket?
