### ISSUE TITLE
No Import .ics

### ISSUE THREAD

**Issue by thewardiknow** [Etar-Group/Etar-Calendar#337]
Perhaps I am just missing it, but there is no import option. Has this been removed? How do you import an .ics file?

**Comment by jspricke** [comment]
Top right below the three dots "import event".

**Comment by thewardiknow** [comment]
Thanks for the quick response, but there is nothing under the three dots.

**Comment by jspricke** [comment]
Which version do you use?
![screenshot_20180615-165551](https://user-images.githubusercontent.com/480915/41474794-3f09284a-70bd-11e8-9279-1dfca388b508.png)

**Comment by thewardiknow** [comment]
1.0.13 downloaded today from f-Droid

**Comment by jspricke** [comment]
Version should be fine. Did you setup a calendar account in Android? Can you add new events by hand?

**Comment by thewardiknow** [comment]
I can add events manually. As for adding a calendar in Android, not sure. I was using "Simple Calendar".

**Comment by jspricke** [comment]
Simple Calendar is unrelated, do you have DAVDroid, Offline Calendar or a Google account?

**Comment by jspricke** [comment]
Import only works for files in the CalendarEvents folder. The menu entry is not shown if the directory does not exist or is empty. Sorry for not remembering faster.
