### ISSUE TITLE
Birthdays in Etar do not match contact birthdays

### ISSUE THREAD

**Issue by jhoc2000** [Etar-Group/Etar-Calendar#339]
I just installed Etar version 1.0.13. It appeared to import the calendar birthday events from my Contacts app but when I looked at the dates of the birthdays, they appear to be a day early in Etar than those entered in the Contacts app.

I'm running Android 6.0.1 on a Sony Xperia Z2. The calendar app is Calendar version 20.3.B.0.3. The calendar I chose is the devise calendar. The contacts app is Contacts version 19.1.A.0.106.

I'm not sure if it's relevant but I'm in Australia. Selecting today in Etar shows today's date.

**Comment by jhoc2000** [comment]
On further investigation Etar hasn't imported the events from the Contacts app. It appears to have included calendar events from somewhere else. 

How can I import events from the Contact app?

**Comment by jspricke** [comment]
I'm not aware of any export function in a Contact app. But there is [Birthday Calendar](https://f-droid.org/de/packages/saschpe.contactevents/) and [Birthday Adapter](https://f-droid.org/de/packages/org.birthdayadapter/), which should do what you are looking for.

**Comment by sebaki** [comment]
Adding a third solution, if you are using a nextcloud instance.
First you need to activate the contacts- and the calendar-app in nextcloud. Then you have to sync your contacts with nextcloud. Afterwards there is an automatically generated calendar called 'Contact birthdays' which is based on your synced contacts. You then can sync this calendar with your phone. For this purpose I recommend [DAVdroid](https://www.davdroid.com/). :-)

**Comment by jhoc2000** [comment]
This option is not available to me as I use no cloud of any type for privacy reasons. I look forward to another solution. 

Thank you. 

John.

**Comment by jspricke** [comment]
There are no other solutions then the three provided above, so closing.
