### ISSUE TITLE
Entered events disappear

### ISSUE THREAD

**Issue by rrthomas** [Etar-Group/Etar-Calendar#354]
I have had this problem on several occasions, where I think I have entered an event, and later I find it has disappeared.

My first thought was that I was accidentally pressing Cancel instead of Done on creating the event. It is certainly true that the Cancel button could be smaller.

However, I am fairly certain this is not the real problem. In particular, I have only had the problem, as far as I am aware, when entering events in one physical location. This location happens to have poor data reception.

I have experienced this problem now about 5 or 6 times over several months, with two different phones.

On at least one of these occasions I saw the "Event created" message after entering it.

I am using version 1.0.13, on Oreo 8.0 on a Sony Xperia XZ1 Compact.

Thanks very much for Etar: it's a great improvement on Google Calendar with the dark theme and the lack of graphical backgrounds for appointments!

**Comment by jspricke** [comment]
Etar safes events only to the local DB, it doesn't do any synchronisation or opens any data connection. As long as you see "Event created", everything should be fine from the Etar side. What do you use to synchronise you events with you online account? I would propose to open an issue with them.

**Comment by rrthomas** [comment]
Thanks very much for getting back to me!

I creating events in my default Google account's calendar, and using the standard Android sync to synchronise the events with my account online. So I guess you're suggesting there's a bug in the Android synchronisation service?

I have never had this problem with Google Calendar, or the stock Android app, which I previously used. But of course that was on a different version of Android.

**Comment by jspricke** [comment]
It's hard to say what and where the bug is. If you want to look into it, I would propose to find a reproducible example and use adb to look into the log and database and trace it over time. But it sounds more like a sync issue (and not an Etar issue) to me.

**Comment by fonfon** [comment]
I connected my Etar calendar with my radicale server using DAVdroid. Everything is setup to be synchronized and displayed, but I do not see any event of the radicale server in Etar.
The connection setup is correct though:
When I add an event it appears in etar until the synchronization kicks in. Then it disappears in etar -- and appears on the server and on thunderbird/lightning.
It feels a bit like black magic ;)

**Comment by rrthomas** [comment]
I traced my problem to the use of Data Saver mode. When I allowed Etar to use unlimited data in Data Saver mode, I did not lose any more appointments. So it looks like an Android bug in the interaction between the calendar service and data saver. I guess you can close this bug.
