### ISSUE TITLE
How to add this project as a library to my project in Android Studio?

### ISSUE THREAD

**Issue by shylendramadda** [Etar-Group/Etar-Calendar#377]
I am trying to make this a module in my project but unfortunately, I can't because of too many errors like

Unable to resolve dependency for ':app@compileOptionsUnitTest/compileClasspath': Could not resolve project :Etar-Calendar.

I followed these steps by referring here https://github.com/MagicMicky/FreemiumLibrary/wiki/Import-the-library-in-Android-Studio:

**Method 1:**

1. Open your project in Android Studio
2. Download this project
3. Create a folder "subProject" in your project
4. Copy and paste the "Etar-Calendar" folder to your subProject folder
5. On the root of the project, the directory created the settings.gradle file. It should contain something like the following:
  include 'MyApp', 
  include ':subProject:Etar-Calendar'
7. gradle clean & build/close the project and reopen/re-import it.
```
dependencies {
//...
    implementation project(':subProject:Etar-Calendar')
}

```

**Method 2:**

1. Opened the project in Android Studio
2. Download this project
3. Go to File > Import Module and import the library as a module
4. Right-click your app in project view and select "Open Module Settings"
5. Click the "Dependencies" tab and then the '+' button
6. Select "Module Dependency"
7. Select "Etar-Calendar"

but same issues like "Unable to resolve dependency for ':app@compileOptionsUnitTest/compileClasspath': Could not resolve project :Etar-Calendar. "

**Comment by jspricke** [comment]
This is not a Etar issue.

**Comment by shylendramadda** [comment]
Can you please help on this issue?
