### ISSUE TITLE
PC sync - creating new calendars

### ISSUE THREAD

**Issue by LinusEngel** [Etar-Group/Etar-Calendar#410]
The only calendar I can choose from is called "PC sync", which I can't change. Neither can I add another calendar, e.g. private or work, for which I would like to assign a different colour etc.
Or is this only possible by importing existing google calendars / .ics files?
Can someone please include more instructions concerning this?

**Comment by jspricke** [comment]
Etar is only there to view and edit existing calendars. If you want to add new once, Android has the concept of adapters and accounts. So for a local calendar, you can use [Offline Calendar](https://f-droid.org/repository/browse/?fdfilter=calendar&fdid=org.sufficientlysecure.localcalendar) and for a remote CalDAV there is [DAVdroid](https://f-droid.org/repository/browse/?fdfilter=davdroid&fdid=at.bitfire.davdroid) for example.
