### ISSUE TITLE
Webdav events not editable

### ISSUE THREAD

**Issue by raduad** [Etar-Group/Etar-Calendar#438]
This is not a bug or feature request (yet). I'm only asking this: are existing events from a webdav calendar supposed to be un-editable? I wanted to change the date of an event and I wasn't able, but creating a new event and then modifying it works.

**Comment by jspricke** [comment]
What do you mean by not able to change? Is there no button to edit or did it not accept the edit afterwards? This sounds like an issue with your webdav sync or server.

**Comment by raduad** [comment]
I mean I have the event in the calendar and there's no button to edit it. There's only Share, Export and Delete buttons. I just noticed that only some events are not editable, but I don't know what could be the reason for that.

**Comment by jspricke** [comment]
The edit button is hidden if the calendar is marked as read only or if you are not the organizer:
https://github.com/Etar-Group/Etar-Calendar/blob/master/src/com/android/calendar/EventInfoFragment.java#L1729
This is probably due to your sync adapter or server.

**Comment by raduad** [comment]
> The edit button is hidden if the calendar is marked as read only or if you are not the organizer:
> https://github.com/Etar-Group/Etar-Calendar/blob/master/src/com/android/calendar/EventInfoFragment.java#L1729
> This is probably due to your sync adapter or server.

Thanks for the answer... I imported the events from google calendar and, as I said, some of them are editable and others are not. Not sure why, because I created them all so I should be the organizer. Anyway, I have no problem deleting them and creating new ones. I don't have too many events.

**Comment by ovz93br43v7** [comment]
I have the same problem. I switched from aCalender+ to etar. With aCalender+ I was able to edit every event in may shared calender and in etar only for new events.
Is it somehow possible to activate the edit function?
