### ISSUE TITLE
Etar Crashes On Opening - Won't Run

### ISSUE THREAD

**Issue by 0pLuS0** [Etar-Group/Etar-Calendar#441]
Hello,

Etar won't run, it just crashes after I first start it and grant the permissions.

I've attached a Logcat, I hope it will show you something so it can be fixed on either end.

I'm running a debloated version of OxygenOS 5.1.7 Oreo 8.1.0 that has microG instead of GSF.

[logcat.txt](https://github.com/Etar-Group/Etar-Calendar/files/2858296/logcat.txt)

Thanks

```P.S. I really want to run Etar, so I hope this can be resolved soon.```

**Comment by 0pLuS0** [comment]
Ok I had ```CalendarProvider``` removed from my ROM, now Etar is running, but every time I start it, the microG login comes up, I'm assuming Etar wants us logged into a Google Account before using? 

I thought this being an Open Source Calendar it's not going to be tied to Google, so how can Etar be run without being associated to a Google Account?

When I look at the Phone Settings I see google.com as a supported link with Etar...

Hmm

**Comment by jspricke** [comment]
Etar will not work without a CalendarProvider, so closing.

**Comment by 0pLuS0** [comment]
I figured that out as I mentioned in my last reply, sorry about that... :(
