### ISSUE TITLE
Can't sync with DAVdroid

### ISSUE THREAD

**Issue by shootheart** [Etar-Group/Etar-Calendar#495]
I have added a sync account on the DAVdroid, but when I try to add an event, Etar once again prompts me to add an account.

**Comment by ByteHamster** [comment]
Have you enabled the calendar in DavDroid? You might need to manually sync again, too.

**Comment by shootheart** [comment]
> Have you enabled the calendar in DavDroid? You might need to manually sync again, too.

I have enabled it and DavDroid could sync calendar from cloud, but Etar couldn't detect it. 
My rom is lineageOS 16. So I'm not sure if it's a bug in the system or software.

**Comment by ByteHamster** [comment]
Do other apps display the calendar?

Other things that might fix the problem:

- Try rebooting
- Have a look at the sidebar entry `Calendars to display`

**Comment by shootheart** [comment]
It's empty when I click Calendars to display.
In fact, the default calendar also can not be synchronized, and the system will release an updated every day.

**Comment by rparkins999** [comment]
Try clicking CALENDARS TO SYNC at the bottom of the Calendars to display page: if it's a new calendar to your Android device, you have to sync it before ETAR can see it. If it isn't in either the display list or the sync list, DavDroid probably isn't syncing it properly: check the sync setup on DavDroid.

Another possibility is to check with Calendar Import-Export (https://github.com/SufficientlySecure/calendar-import-export) and see if that can see the calendar.
