### ISSUE TITLE
Widget removed with update 1.0.16?

### ISSUE THREAD

**Issue by th-lamb** [Etar-Group/Etar-Calendar#504]
The widget stopped working after update to version 1.0.16. (Error message "Unable to load" or similar.)

Now, the widget is not in the list of widgets anymore. The app itself can still be used.

Device: MotoG3
OS: Lineage OS 14.1-20190220

**Comment by jspricke** [comment]
see the changelog: https://github.com/Etar-Group/Etar-Calendar/releases/tag/v1.0.14
and the issue: https://github.com/Etar-Group/Etar-Calendar/issues/417
