### ISSUE TITLE
Why does ETAR force HAS_ATTENDEES to 1?

### ISSUE THREAD

**Issue by rparkins999** [Etar-Group/Etar-Calendar#518]
Forcing HAS_ATTENDEES to 1 causes problems with some PC calendar editors (such as Evolution) which refuse to save an edited event if it has attendees but the attendee list is empty.

**Comment by dilyanpalauzov** [comment]
How is HAS_ATTENDES mapped in the iCalendar file and communicated to Evolution?

**Comment by rparkins999** [comment]
My Android calendar is synchronised to a Radicale server on my PC using DavDroid (aka Davx5), and Evolution is also sychronised with the same Radicale server. However the issue isn't with Evolution, which is just an example of an application which doesn't like a calendar entry which HAS_ATTENDEES but has no attendees in its attendees list. RFC 5545 says in section 3.8.4.1 "This property MUST be specified in an iCalendar object  that specifies a group-scheduled calendar entity." So if a calendar entry HAS_ATTENDEES it must have some attendees.

**Comment by dilyanpalauzov** [comment]
I did not understood from your answer, how is HAS_ATTENDEES mapped in the iCalendar file.
