### ISSUE TITLE
Run at boot

### ISSUE THREAD

**Issue by hungerburg** [Etar-Group/Etar-Calendar#542]
Today I had an event with reminder, though I got nothing, no sound, no message. There was a reboot between entering the event and time of event. Do I have to start Etar at least once after reboot for notifications? Can this be automated?

**Comment by jspricke** [comment]
Etar desn't need to be started after boot. I would propose to continue the discussion in #521.

**Comment by hungerburg** [comment]
Hallo Jochen, indeed, I created an event, rebooted the device, notification with sound came up just fine. (This with downgraded etar.)
