### ISSUE TITLE
[Suggestion] Windows and Linux?

### ISSUE THREAD

**Issue by underlineGalaxy** [Etar-Group/Etar-Calendar#550]
Hello Devs. I just wanna say this is an amazing app... if not for one thing: it isn't crossplatform. I used it for 6 months and had a blast with it, used a lot of the features that where very awesome to me.

The thing is, there isn't actually much good open source calendars out there, especially ones that allow for a selfhosted or a server (like nextcloud) sync, or even at least attempt to do aesthetics to some degree! Seriously, this might be the most beautiful open source calendar out there.

I think these are the reasons it would stand out as a crossplatform calendar, and thus IMO get a pretty hefty userbase on these other systems to the point of matching development costs.

Thanks for reading this. I hope you guys consider it.

**Comment by jspricke** [comment]
Windows and Linux are very different to program, so this would be an entire different application.
