### ISSUE TITLE
Sync Failure

### ISSUE THREAD

**Issue by markbryanduncan** [Etar-Group/Etar-Calendar#561]
Fails to sync.

--- BEGIN DEBUG INFO ---
Account name: markbryanduncan@e.email
Authority: com.android.calendar

HTTP REQUEST:
Request{method=PUT, url=https://ecloud.global/remote.php/dav/calendars/markbryanduncan@e.email/marks-icloud-calendar/fac86a89-7546-479a-aa27-b5ee320f1bfa.ics, tags={}}
BEGIN:VCALENDAR
VERSION:2.0
PRODID:+//IDN e.foundation//Account Manager/2.0.5-ose ical4j/2.2.0
BEGIN:VEVENT
DTSTAMP:20190927T174854Z
UID:fac86a89-7546-479a-aa27-b5ee320f1bfa
SUMMARY:Test
LOCATION:Home
DTSTART;TZID=Africa/Johannesburg:20190927T200000
DURATION:PT1800S
RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=FR
CLASS:PRIVATE
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:PT0S
ACTION:DISPLAY
DESCRIPTION:Test
END:VALARM
END:VEVENT
BEGIN:VTIMEZONE
TZID:Africa/Johannesburg
TZURL:http://tzurl.org/zoneinfo/Africa/Johannesburg
X-LIC-LOCATION:Africa/Johannesburg
BEGIN:STANDARD
TZOFFSETFROM:+0152
TZOFFSETTO:+0130
TZNAME:SAST
DTSTART:18920208T003000
RDATE:18920208T003000
END:STANDARD
BEGIN:STANDARD
TZOFFSETFROM:+0130
TZOFFSETTO:+0200
TZNAME:SAST
DTSTART:19030301T003000
RDATE:19030301T003000
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0200
TZOFFSETTO:+0300
TZNAME:SAST
DTSTART:19420920T020000
RDATE:19420920T020000
RDATE:19430919T020000
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0300
TZOFFSETTO:+0200
TZNAME:SAST
DTSTART:19430321T020000
RDATE:19430321T020000
RDATE:19440319T020000
END:STANDARD
END:VTIMEZONE
END:VCALENDAR

HTTP RESPONSE:
Response{protocol=h2, code=403, message=, url=https://ecloud.global/remote.php/dav/calendars/markbryanduncan@e.email/marks-icloud-calendar/fac86a89-7546-479a-aa27-b5ee320f1bfa.ics}
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message>Permission denied to create file (filename fac86a89-7546-479a-aa27-b5ee320f1bfa.ics)</s:message>
</d:error>

LOCAL RESOURCE:
LocalEvent=[eTag=null, fileName=fac86a89-7546-479a-aa27-b5ee320f1bfa.ics, flags=0, weAreOrganizer=true, calendar=foundation.e.accountmanager.resource.LocalCalendar@edde981, event=Event=[alarms=[BEGIN:VALARM
TRIGGER:PT0S
ACTION:DISPLAY
DESCRIPTION:Test
END:VALARM
], attendees=[], classification=CLASS:PRIVATE, color=null, description=null, dtEnd=null, dtStart=DTSTART;TZID=Africa/Johannesburg:20190927T200000, duration=DURATION:PT1800S, exDates=[], exRule=null, exceptions=[], lastModified=null, location=Home, opaque=true, organizer=null, rDates=[], rRule=RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=FR, recurrenceId=null, status=STATUS:CONFIRMED, summary=Test, unknownProperties=[], sequence=0, uid=fac86a89-7546-479a-aa27-b5ee320f1bfa, shadow$_klass_=class foundation.e.ical4android.Event, shadow$_monitor_=0], id=8, shadow$_klass_=class foundation.e.accountmanager.resource.LocalEvent, shadow$_monitor_=0]

REMOTE RESOURCE:
https://ecloud.global/remote.php/dav/calendars/markbryanduncan@e.email/marks-icloud-calendar/fac86a89-7546-479a-aa27-b5ee320f1bfa.ics

EXCEPTION:
foundation.e.dav4android.exception.HttpException: HTTP 403 
	at foundation.e.dav4android.DavResource.checkStatus(DavResource.kt:416)
	at foundation.e.dav4android.DavResource.checkStatus(DavResource.kt:392)
	at foundation.e.dav4android.DavResource.put(DavResource.kt:284)
	at foundation.e.accountmanager.syncadapter.SyncManager$uploadDirty$1$1.invoke(SyncManager.kt:327)
	at foundation.e.accountmanager.syncadapter.SyncManager$uploadDirty$1$1.invoke(SyncManager.kt:59)
	at foundation.e.accountmanager.syncadapter.SyncManager.useRemote(SyncManager.kt:781)
	at foundation.e.accountmanager.syncadapter.SyncManager$uploadDirty$1.invoke(SyncManager.kt:314)
	at foundation.e.accountmanager.syncadapter.SyncManager$uploadDirty$1.invoke(SyncManager.kt:59)
	at foundation.e.accountmanager.syncadapter.SyncManager.useLocal(SyncManager.kt:767)
	at foundation.e.accountmanager.syncadapter.SyncManager.uploadDirty(SyncManager.kt:305)
	at foundation.e.accountmanager.syncadapter.SyncManager$performSync$1.invoke(SyncManager.kt:127)
	at foundation.e.accountmanager.syncadapter.SyncManager$performSync$1.invoke(SyncManager.kt:59)
	at foundation.e.accountmanager.syncadapter.SyncManager.unwrapExceptions(SyncManager.kt:807)
	at foundation.e.accountmanager.syncadapter.SyncManager.performSync(SyncManager.kt:113)
	at foundation.e.accountmanager.syncadapter.EeloCalendarsSyncAdapterService$CalendarsSyncAdapter.sync(EeloCalendarsSyncAdapterService.kt:87)
	at foundation.e.accountmanager.syncadapter.SyncAdapterService$SyncAdapter.onPerformSync(SyncAdapterService.kt:83)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)

SOFTWARE INFORMATION
Package: foundation.e.accountmanager
Version: 2.0.5-ose (248) from 28 May 2019
Installed from: APK (directly)
JB Workaround installed: no

CONNECTIVITY (at the moment)
Active connection: WiFi, CONNECTED

CONFIGURATION
Power saving disabled: no
android.permission.READ_CONTACTS permission: granted
android.permission.WRITE_CONTACTS permission: granted
android.permission.READ_CALENDAR permission: granted
android.permission.WRITE_CALENDAR permission: granted
org.dmfs.permission.READ_TASKS permission: granted
org.dmfs.permission.WRITE_TASKS permission: granted
System-wide synchronization: automatically
Account: markbryanduncan@e.email
  Address book sync. interval: 1440 min
  Calendar     sync. interval: 1440 min
  OpenTasks    sync. interval: 1440 min
  WiFi only: true
  [CardDAV] Contact group method: GROUP_VCARDS
  [CalDAV] Time range (past days): 7
           Manage calendar colors: true
Address book account: Contacts (markbryanduncan@e.email dA)
  Main account: Account {name=markbryanduncan@e.email, type=e.foundation.webdav.eelo}
  URL: https://ecloud.global/remote.php/dav/addressbooks/users/markbryanduncan@e.email/contacts/
  Sync automatically: true

SQLITE DUMP
android_metadata
	|  locale |
	|  en_GB |
----------
services
	|  _id | accountName | authState | accountType | addressBookAccountType | service | principal |
	|  1 | markbryanduncan@e.email | <null> | e.foundation.webdav.eelo | foundation.e.accountmanager.eelo.address_book | carddav | https://ecloud.global/remote.php/dav/principals/users/markbryanduncan@e.email/ |
	|  2 | markbryanduncan@e.email | <null> | e.foundation.webdav.eelo | foundation.e.accountmanager.eelo.address_book | caldav | https://ecloud.global/remote.php/dav/principals/users/markbryanduncan@e.email/ |
----------
sqlite_sequence
	|  name | seq |
	|  services | 6 |
	|  homesets | 6 |
	|  collections | 13 |
----------
homesets
	|  _id | serviceID | url |
	|  2 | 1 | https://ecloud.global/remote.php/dav/addressbooks/users/markbryanduncan@e.email/ |
	|  6 | 2 | https://ecloud.global/remote.php/dav/calendars/markbryanduncan@e.email/ |
----------
collections
	|  _id | serviceID | type | url | privWriteContent | privUnbind | forceReadOnly | displayName | description | color | timezone | supportsVEVENT | supportsVTODO | source | sync |
	|  3 | 1 | ADDRESS_BOOK | https://ecloud.global/remote.php/dav/addressbooks/users/markbryanduncan@e.email/contacts/ | 1 | 1 | 0 | Contacts | <null> | <null> | <null> | 0 | 0 | <null> | 1 |
	|  12 | 2 | WEBCAL | https://ecloud.global/remote.php/dav/calendars/markbryanduncan@e.email/marks-icloud-calendar/ | 1 | 1 | 0 | Mark's iCloud Calendar | <null> | -13325604 | <null> | 1 | 0 | https://p67-caldav.icloud.com/published/2/MzY1MTQ3MTM4MzY1MTQ3MS6NoeeNt07fJcqtSD7vxNFZbzfVAgGTg_5qxhXdz-_mQIr5h6x9zeI-jf9ffFPfDuzBEhGQ7r8f_6chhVKdd2g | 1 |
	|  13 | 2 | CALENDAR | https://ecloud.global/remote.php/dav/calendars/markbryanduncan@e.email/tasks/ | 1 | 1 | 0 | Tasks | <null> | <null> | <null> | 0 | 1 | <null> | 1 |
----------

SYSTEM INFORMATION
Android version: 7.1.2 (lineage_i9300-userdebug 7.1.2 NJH47F 20190925 dev-keys)
Device: samsung GT-I9300 (m0)

--- END DEBUG INFO ---

**Comment by jspricke** [comment]
This is unrelated to Etar (Etar has no sync feature itself).
Based on the data I would propose to ask the e foundation.
