### ISSUE TITLE
No Sync with deactivated Google Calendar

### ISSUE THREAD

**Issue by elmar69** [Etar-Group/Etar-Calendar#569]
Etar Calendar seems not to sysc with google calendar data once googles calendar-app  (com.google.android.calendar) is deactivated. 
Is there an alternative Sync-Service to be installed?
I'm using LineAgeOS with gApps installed.

**Comment by jspricke** [comment]
Etar has no sync capabilities in itself, you can use other Apps for this. see: https://github.com/Etar-Group/Etar-Calendar#how-to-use-etar.
