### ISSUE TITLE
Fails to build because of lint failure in colorpicker

### ISSUE THREAD

**Issue by YtvwlD** [Etar-Group/Etar-Calendar#578]
I tried to clone this repository and build the app and the build failed with this message:

```
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  
  Errors found:
  
  /home/niklas/dev/Etar-Calendar/external/colorpicker/build.gradle:11: Error: Google Play requires that apps target API level 26 or higher.
   [ExpiredTargetSdkVersion]
          targetSdkVersion 17
          ~~~~~~~~~~~~~~~~~~~
```

I added this `abortOnError false` to the appropriate section in the main `build.gradle` and the app builds, but I'm not quite sure if I'm doing anything wrong.
Also, this is the only section that does not have that part. Should I open a PR to add this?

Also, why is the colorpicker targeting SDK version 17?

**Comment by jspricke** [comment]
All git submodules in the externals directory are directly imported from Google. We should probably add patches to them with an updated number. Will do it later.

**Comment by YtvwlD** [comment]
I see.
But I think it still makes sense to not treat lint errors there as fatal. This is already been done for all other external dependencies, so I created #579 for the sake of consistency.

**Comment by jspricke** [comment]
oh, you are totally right, thx :).
