### ISSUE TITLE
Build not successful

### ISSUE THREAD

**Issue by ferguquang** [Etar-Group/Etar-Calendar#586]
I tried to get your sourcecode, but when the build failed, an error occurred:
ERROR: Cannot read packageName from Q:\Android\Calendar2\Etar-Calendar\external\timezonepicker\src\main\AndroidManifest.xml
Package "external" has problem?
Help me, thank you!

**Comment by jspricke** [comment]
Please read the build instructions here: https://github.com/Etar-Group/Etar-Calendar#build-instructions
Sounds like you are missing the `git submodules` step.
Closing as not a bug.
