### ISSUE TITLE
Event created in ETAR doesn't feed into Google calendar

### ISSUE THREAD

**Issue by zelmor** [Etar-Group/Etar-Calendar#593]
Steps to replicate:
I have the calendar storage running on my phone, but disabled Google Calendar itself. 
I have created an event in ETAR, under my email address. The event is created, and the ToDo widget sees it as well. However, when checking via Web, the event is not visible in Google Calendar.

Fix:
Enabling the Google Calendar Android application causes the events to sync.

Expected behaviour: ETAR should use the built in Android calendar storage to sync to Google accounts, and not depend on Google's proprietary application.

**Comment by jspricke** [comment]
https://github.com/Etar-Group/Etar-Calendar#how-to-use-etar

**Comment by zelmor** [comment]
Mea culpa.
