### ISSUE TITLE
Add options to 'Show Me As'

### ISSUE THREAD

**Issue by SophieYoonseo** [Etar-Group/Etar-Calendar#595]
I want to modify the 'show me as' part. I can be busy and available. 
But sometimes we are in an ambiguous situation that is neither too busy nor too leisurely. Therefore, it would be nice to add two more options like 'too busy', 'a bit busy', 'available',  'free'. Let me know if there are more appropriate expressions.

If you think it's not good, I have one more idea.

How about adding the function to express our feelings? Like 'show me as', we can express ourselves whether we feel good or bad or angry.

What do you think of my opinions?

**Comment by jspricke** [comment]
The definition is according to https://tools.ietf.org/html/rfc5545#section-3.2.9:

> Applications MUST treat x-name and iana-token values they don't recognize the same way as they would the BUSY value.

So you have to change the RFC (and all implementations), if you really want to change this.
