### ISSUE TITLE
I want to add a d-day function on this calendar

### ISSUE THREAD

**Issue by Comprehensible7** [Etar-Group/Etar-Calendar#612]
Hi!

I really like this Calendar, very nice design and functions...

Thank you for providing this application

Anyway I have one question

I`d like to know how can I add a D-Day function on this calendar?

I really want to know how it works...

Please let me know if possible to add this function

Thanks!

**Comment by Comprehensible7** [comment]
+ I would appreciate it if you could let me know if the above mentioned features are available.

Thank you

**Comment by jspricke** [comment]
What is a D-Day function?

**Comment by Comprehensible7** [comment]
> What is a D-Day function?

The concept of calculating the date.
For example, we count the end date from October 1 to October 30.
Calculating how many days are left from October 1 to 30.

Thanks

**Comment by jspricke** [comment]
I guess d-day means due day?
Do you want to have a daily reminder how many days are left to the event date?
Maybe something like a `VTODO` entry?
At the moment this is not possible. #83 is proposing to add display `VTODO` entries.

**Comment by Comprehensible7** [comment]
> I guess d-day means due day?
> Do you want to have a daily reminder how many days are left to the event date?
> Maybe something like a `VTODO` entry?
> At the moment this is not possible. #83 is proposing to add display `VTODO` entries.

Exactly, it`s kind of that things 

I`ll check this session #83 

Appreciate it 

Thank you
