### ISSUE TITLE
Email notification is never sent

### ISSUE THREAD

**Issue by curioustwo** [Etar-Group/Etar-Calendar#635]
How do I set this up? There is no place to enter email address etc. so I shouldn't be surprised it doesn't work. :-)

**Comment by dilyanpalauzov** [comment]
Sending email notifications is a matter of configuring the server correctly.

**Comment by curioustwo** [comment]
I don't see any settings to configure the mail server in the program. I am using a DavX5 connected calendar.

**Comment by dilyanpalauzov** [comment]
I mean the iCalendar data is uploaded over CalDAV to the server and the CaDAV server needs to be configured to send reminders.

**Comment by curioustwo** [comment]
Thanks!
