### ISSUE TITLE
Crash when opening settings [new in 1.0.20]

### ISSUE THREAD

**Issue by AlexanderRitter02** [Etar-Group/Etar-Calendar#641]
Etar app crashes after clicking on **settings** in sidebar.
Crash started happening after recent update to 11.0.20

## Device
_Device:_ Nokia 7+
_Android_: 9
_Etar-Version_: 11.0.20 (F-droid)
_Permissions:_ Calendar, Contacts, Storage

Additionally, I'm using [Offline Calendar](https://f-droid.org/en/packages/org.sufficientlysecure.localcalendar/) for local calendars.

## Crash Log
[etar_crash.txt](https://github.com/Etar-Group/Etar-Calendar/files/4144262/etar_crash.txt)

```
02-02 15:06:43.428  2563  2563 D StatusBar: hiding the MENU button
02-02 15:06:43.429  1465  1889 I ActivityManager: Displayed ws.xsoh.etar/com.android.calendar.settings.SettingsActivity: +125ms
02-02 15:06:43.431  5103  7745 D ContentProvider: checkPermissionAndAppOp, ws.xsoh.etar want to check android.permission.READ_CALENDAR(8) was skipped. 8/9
02-02 15:06:43.434  1465  2425 D WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 19 num clients 1
02-02 15:06:43.435  1465  2425 D WifiTrafficPoller:  packet count Tx=1564 Rx=1642
02-02 15:06:43.444   795   943 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
02-02 15:06:43.454  9322  9322 E AndroidRuntime: FATAL EXCEPTION: main
02-02 15:06:43.454  9322  9322 E AndroidRuntime: Process: ws.xsoh.etar, PID: 9322
02-02 15:06:43.454  9322  9322 E AndroidRuntime: java.lang.IllegalStateException: name must not be null
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at com.android.calendar.persistence.CalendarRepository$CalendarLiveData.getContentProviderValue(CalendarRepository.kt:73)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at com.android.calendar.persistence.CalendarRepository$CalendarLiveData.getContentProviderValue(CalendarRepository.kt:55)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at com.android.calendar.persistence.ContentProviderLiveData$getContentProviderValueAsync$1$accounts$1.invokeSuspend(ContentProviderLiveData.kt:60)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:874)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:198)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6729)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-02 15:06:43.454  9322  9322 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-02 15:06:43.457  1465  8535 W ActivityManager:   Force finishing activity ws.xsoh.etar/com.android.calendar.settings.SettingsActivity
02-02 15:06:43.458  1465  8535 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
02-02 15:06:43.459  1004  1181 W statsd  : not interested in atom 130601
02-02 15:06:43.460   795   943 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
02-02 15:06:43.460  1465  1819 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{16397ef u0 ws.xsoh.etar/com.android.calendar.settings.SettingsActivity}
02-02 15:06:43.460  1465  1819 D StatusBarManagerService: disableLocked net1 = 0; net2 = 0 pkg=Window{16397ef u0 ws.xsoh.etar/com.android.calendar.settings.SettingsActivity}
02-02 15:06:43.461  2563  2563 D StatusBar: hiding the MENU button
02-02 15:06:43.462  1465  8535 W ActivityManager:   Force finishing activity ws.xsoh.etar/com.android.calendar.AllInOneActivity
```

**Comment by dschuermann** [comment]
Hey @AlexanderRitter02 ,

what other calendars do you have besides Offline Calendar?

**Comment by meaz** [comment]
I have the same issue. I use nextcloud calendars. I don't use offline calendar.

**Comment by licaon-kter** [comment]
Same here, Android 10, but no other calendar installed.

**Comment by ThinkTwiceCodeOnce-prog** [comment]
Same here since v1.0.20, Android 9. App crashes, when Settings under Menu is selected.

**Comment by dschuermann** [comment]
My attempt to fix this bug is in https://github.com/Etar-Group/Etar-Calendar/pull/643

The crash happens because of a calendar without a ``name`` attribute, which is only the internal name. In case of davx5 ``name`` should be something like "https://nextcloud.example.com/remote.php/dav/calendars/...". Weird that there are calendars without an internal name.

**Comment by AlexanderRitter02** [comment]
No other calendars installed except Offline Calendar.
There is a calendar with my google mail adress, however unused.
I know of a Default Calendar too I never used.

Thank you for the fix, I will comment if works fine.

**Comment by dschuermann** [comment]
> I know of a Default Calendar too I never used.

Ah, that could be the culprit.

**Comment by AlexanderRitter02** [comment]
Indeed it was the fault of **Default Calendar**. 😃
Nonetheless it's useful to have the crash fixed just in case.

Since I had some time to spare I built the Etar version with the fix included and it worked.
After confirming it crashed in "old" Etar and didn't with the latest commit, I decided to delete the Default Calendar and voilà, "old" Etar didn't crash anymore too.


Thanks you for your help and for resolving this quickly. I appreciate your work.

**Comment by meaz** [comment]
Though things are fixed, I still don't understand the Default Calendar things. Is that a default calendar created by Android? How can it be removed then?
Also, as for calendar "internal name" how is that possible to have a NextCloud calendar with no names?

**Comment by SubSi** [comment]
I still have this crash-problem. I cannot delete or deactivate the device´s default Kalender-app. Since Etar keeps crashing when opening settings I cannot add the phone calendar to shown calendars.
Huawei HMA-L29, Android 10

**Comment by jspricke** [comment]
The fixed version is released and should be available soon. Please 
downgrade or wait new the release.

**Comment by dschuermann** [comment]
> Though things are fixed, I still don't understand the Default Calendar things. Is that a default calendar created by Android? How can it be removed then?
> Also, as for calendar "internal name" how is that possible to have a NextCloud calendar with no names?

AFAIK, some phone vendors ship custom Android OS where a Default Calendar is available. Also, I know that you can create local calendars with some proprietary calendar apps, such as aCalendar+. Maybe these have no internal name.
Nextcloud calendars with davx5 should always have an internal name.
