### ISSUE TITLE
Synchronization with DAVX does not work ?

### ISSUE THREAD

**Issue by j3r3m1** [Etar-Group/Etar-Calendar#660]
Hi,
i use Davx and Etar since 6 months on a lineage phone. First, everything went well but since few weeks, I have no synchronization of my phone calendar anymore.
In DavX I have sync my nextcloud account and I can choose which calendar to synchronize. I have select all of them. However nothing appears in Etar, it only proposes me to add a new account (through Davx), thing that I have already done...

I have tried to reinstall both Etar and Davx but the problem remains. Do you have an idea ?

My config
Android 7.1.2
Davx 2.6.3.1-ose
Etar 1.0.21

**Comment by dschuermann** [comment]
This has nothing to do with Etar, because Etar only displays events. The synchronization is done by Davx5. Please check out their faq: https://www.davx5.com/faq/synchronization-is-not-run-as-expected

**Comment by j3r3m1** [comment]
Ok it did not solve the problem but I will investigate this direction. Thanks
