### ISSUE TITLE
display contacts birthay in the calendar

### ISSUE THREAD

**Issue by ben-iks** [Etar-Group/Etar-Calendar#664]
Hello everyone , sorry it's more a request than an issue
Is-it possible to display birthday's contacts into the calendar or maybe in a next version ?

By the way, great app, really like it, good job

**Comment by just-Nob** [comment]
It's possible to do that by a third party tool - just have a look at _birthday adapter_ or _birthday calendar_ (available at F-Droid), both giving you the desired functionality.
I'm using _birthday adapter_ for years and don't wanna mid it anymore!

**Comment by ben-iks** [comment]
It's working perfectly, great thanks

**Comment by just-Nob** [comment]
:-)

So maybe you like to close that issue?
I think it's not necessary to blow up an app with functionality that can easily be added by an (open source) third party tool.
