### ISSUE TITLE
Copy a task? 

### ISSUE THREAD

**Issue by bjlockie** [Etar-Group/Etar-Calendar#666]
Is there a way to copy an entry?

**Comment by just-Nob** [comment]
I like to have that possibility as well.


I'm hardly missing the possibility to copy/duplicate a single date entry.
This should work similar to moving an entry, but the original entry still stays unchanged.
This is a feature I often like to use for a series of similar dates/appointments (like a training course), but with slightly different content, or where the date's day and/or time doesn't follow any regularity (example: first date of sequence is on Monday 8:00 a.m for 3h., second on Wednesday 10:00 a.m for 1,5h., third on Thursday 4:30 p.m. for 1h, fourth on Friday 9:15 a.m. for 2h etc.).

**Comment by Hubert21** [comment]
Hi
I second that request!

**Comment by Knote9** [comment]
Absolutely Agree.
It's the only gap I have with the app.
Please prioritise! Thanks.

**Comment by SilverPuppy** [comment]
I commented in #749, but will comment here too. This is important to me as well. Not having it requires rescheduling a previous event, destroying its record. I would love to have this available.

**Comment by tkrypton** [comment]
Hi, yes, this feature would make dump the google calendar completely!
