### ISSUE TITLE
How to fetch google calendar Settings?

### ISSUE THREAD

**Issue by kksingla** [Etar-Group/Etar-Calendar#679]
Thank you for amazing lib...

I want to fetch notification & email default time from google calendar.

![image](https://user-images.githubusercontent.com/18482328/78423238-a6885500-7682-11ea-9bfd-2e502c38589b.png)

**Comment by kksingla** [comment]
@bradfitz @kruton @dsandler @jham 
please help

**Comment by jspricke** [comment]
not an issue.
