### ISSUE TITLE
Stop offline calendar app

### ISSUE THREAD

**Issue by jedie** [Etar-Group/Etar-Calendar#698]
I doesn't recognized that the offline calendar app is deprecated and moved into etar. So I installed them and create Calender's with it ;(

Whould be great if a new version of offline calendar app will inform the user that it's deprecated.

**Comment by dschuermann** [comment]
When I deprecated Offline Calendar, I pushed a new version to Google Play that notifies users that they should move to Etar. Looks like the version hasn't been published on F-Droid. Will check that.

**Comment by dschuermann** [comment]
I made a git tag for 1.9 of Offline Calendar. Should be picked up by the F-Droid build server. 1.9 notifies the user that they should move to Etar.
