### ISSUE TITLE
"Export to SD Card" not working in Android 10, bug found.

### ISSUE THREAD

**Issue by ploink** [Etar-Group/Etar-Calendar#701]
When I open a calendar event and press the "Export to SD" icon, I get a toast message "Problems encountered while sharing event". This also happens on my wife's phone. Both phones run Android 10, so I guess this is A10 related.

The only info I found in logcat:

`05-17 20:34:38.009 E/EventInfoFragment(22264): Couldn't generate ics file`

After some searching and compiling/debugging the app I found the solution at
https://stackoverflow.com/questions/56821095/android-q-file-mkdirs-returns-false

I added the `android:requestLegacyExternalStorage="true"` attribute to the application tag in the manifest and presto! You may also implement Android 10 scoped storage, but that looks like a lot of work. The requestLegacyExternalStorage thing will do fine for now.

---

Unrelated, I checked out the HEAD branch and bumped into an issue that broke installation of the compiled apk. This addition (boldface) to the manifest fixed it:

<provider android:name="com.android.calendar.CalendarRecentSuggestionsProvider"
            android:exported="false"
            **android:authorities="${applicationId}.CalendarRecentSuggestionsProvider"** />

I suppose the HEAD branch is WiP and you may have fixed that already though.

**Comment by jspricke** [comment]
Hi, thanks for looking into this. Can you open a pull request with the change?
The manifest problem is tracked in #696.
