### ISSUE TITLE
Adding shared google (group) calendar.

### ISSUE THREAD

**Issue by petrhejna** [Etar-Group/Etar-Calendar#704]
Is there any way how to add shared google calendar into Etar? 
- link example: adfiuiokq9jtac8t9keomc00b0@group.calendar.google.com
- I haven't found a way via DAVx5 nor natively in Etar

Thank you.

**Comment by jspricke** [comment]
Do you want to subscribe to a ics calendar via URL?
Try https://f-droid.org/de/packages/at.bitfire.icsdroid/
Closing as not an Etar issue.
