### ISSUE TITLE
Is it possible to update the number in the icon dynamically?

### ISSUE THREAD

**Issue by MyNameIsTroll** [Etar-Group/Etar-Calendar#711]
![image](https://user-images.githubusercontent.com/31790025/83261025-026ee600-a1bb-11ea-818b-ddca03d4407c.png)

I was wondering if it was possible to change the number (30) in the Etar icon dynamically, that it changes according to today's date. A bit like the calendar icon on MacOS, but I don't know if it's possible under Android.

![image](https://user-images.githubusercontent.com/31790025/83260099-790ae400-a1b9-11ea-86b4-6b07aef21328.png) ![image](https://user-images.githubusercontent.com/31790025/83260114-7f995b80-a1b9-11ea-8178-dd8e4d1cbc4b.png)

If it's not feasible, why not use a more generic icon without a number for example. 
I think that might be a bit confusing for some users.

![image](https://user-images.githubusercontent.com/31790025/83260479-27168e00-a1ba-11ea-98ee-b8040a851a46.png) ![image](https://user-images.githubusercontent.com/31790025/83260577-52997880-a1ba-11ea-8ce2-f9aa9232a596.png)

**Comment by jspricke** [comment]
Afaik that would need a widget, feel free to provide a patch.
We can discuss changing the icon, but that one doesn't really looks appealing. Feel free to send an icon with a copyright statement as a PR.

**Comment by MyNameIsTroll** [comment]
![image](https://user-images.githubusercontent.com/31790025/83264290-284ab980-a1c0-11ea-9c4e-bcc6b8644674.png)

It works with the Samsung calendar though :/

The generic icons were just an example, it wasn't a graphical proposal ^^

**Comment by jspricke** [comment]
https://stackoverflow.com/a/34617982

**Comment by MyNameIsTroll** [comment]
@jspricke 
thanks for the link, I didn't realize how hard it was to do ^^
I love the application, I had installed it on a friend's phone and he asked me if it was a bug that the number didn't change... that's why I came to create this ticket, as I'm not a developer I didn't realize the feasibility. 
Thank you for your answers.

**Comment by ThirtySomething** [comment]
@jspricke I will also appreciate a dynamic icon. On my Xiaomi Pocophone F1 I used first the Google Calendar. This one does have those dynamic icons. Then I installed Lineage OS on my mobile. The Google Calendar still works as expected. Then I've switched to the default calendar of Lineage OS, Etar. And I'm missing this feature. Are there any news about a possible implementation?

Mobile: [Xiaomi Pocophone F1](https://en.wikipedia.org/wiki/Xiaomi_Pocophone_F1)
OS: [Lineage OS](https://download.lineageos.org/beryllium)
Launcher: [Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=de&gl=US)

**Comment by jspricke** [comment]
@ThirtySomething Please send a pull request with a patch for discussion.

**Comment by ThirtySomething** [comment]
@jspricke I'm sorry, i guess there is a misunderstanding. I so not have an patch. I'm missing this feature and before opening a new issue I searched the issues and found this one. The only thing I did was commenting this issue with my wish...

**Comment by Noitarud** [comment]
This may help:
https://stackoverflow.com/questions/77899320/can-we-change-app-icon-dynamically-without-requiring-store-update
