### ISSUE TITLE
Feature Request: Copy & Move Events in same or different calendar

### ISSUE THREAD

**Issue by e-t-l** [Etar-Group/Etar-Calendar#749]
Related to #666, it would be great to be able to duplicate an event (or even multiple events at a time!) as well as move events from one calendar to another.

**Comment by petrhejna** [comment]
This also provides workaround for "edit calendar". One can duplicate event into different one and then delete original one.

**Comment by dilyanpalauzov** [comment]
For events with attendees managed over CalDAV (“scheduled events”) either the move must be done with the HTTP MOVE verb (to my knowledge currently not supported by DavX5), or all attendees will get a cancellation notification , sent by the server, for the old calendar, and a new meeting invitation for the new calendar (this is what the DELETE and PUT http verbs request)

To avoid the above confusion, Cyrus Imap disallows to have for the same users two events in different calendars with the same UID.  So if this is implemented for events without attendees, and the order of DELETE and PUT is unclear, the UID must be changed.

**Comment by SilverPuppy** [comment]
I second the need for this feature. My current workaround is just to reschedule the old event, but that destroys the record of the old event. Not ideal. Please implement this as you are able.

**Comment by MathieuSchopfer** [comment]
I think #87 should be implemented first. It would provide the base for this task.

**Comment by Cwpute** [comment]
Regarding the asked feature of moving events between calendars, this has éeen requested before in #62 and is being worked on (see draft in linked issue).

**Comment by Thatoo** [comment]
Can't this issue be closed now?
