### ISSUE TITLE
How to add a calendar (.ics file or adress)

### ISSUE THREAD

**Issue by arnauldb** [Etar-Group/Etar-Calendar#767]
Hello,
I've been using Etar happily for a few months with a hosted calendar on my server. I am trying now to add a calendar for French holidays. This calendar is either a .ics file or an address https://www.thunderbird.net/media/caldata/FrenchHolidays.ics

But it seems I can't add it to Etar, I already have my hosted calendar and when I wish to add the .ics file there is no option for this and if I try the address https://www.thunderbird.net/media/caldata/FrenchHolidays.ics Etar asks for a certificate I don't have.

Any help appreciated.

**Comment by jspricke** [comment]
Etar does not sync calendars, try DAVx5 for example. See https://github.com/Etar-Group/Etar-Calendar#how-to-use-etar
