### ISSUE TITLE
Feature request: allow disabling reminders per-calendar

### ISSUE THREAD

**Issue by runejuhl** [Etar-Group/Etar-Calendar#783]
(I looked through the issues and didn't find anything similar; hope I didn't miss anything)

I have a bunch of calendars that are shared, and one of the things that quickly becomes an issue is when I'm interested in seeing calendar events from shared calendars and these have reminders set. This means that I often get a bunch of reminders for events that I have no need to be reminded for.

Would it be possible to add a toggle for disabling reminders per-calendar? It could also be part of DAVx5/other synchronization software, but I feel that it'd be better to have the feature in Etar.

**Comment by ploink** [comment]
I have exactly the same issue and suggest adding a toggle "Enable notifications" just below the "Display events" in the calendar options.

**Comment by ploink** [comment]
I have looked at the source code how to implement this, but need some feedback.

Adding a switch in the calendar settings is easy, but implementing the functionality is tricky and can be done in multiple ways:

1. In the android calendar database there is a column [ALLOWED_REMINDERS](https://developer.android.com/reference/android/provider/CalendarContract.CalendarColumns#ALLOWED_REMINDERS) to do just what we need, but it is readonly for calendar apps and can only be written by sync adapters. Etar may read and honor this setting, but changing it depends very much on the backend. For a local calendar it is impossible to change.
2. One alternative is to store a separate per-calendar setting in the Etar settings database. But, looking at the source code, there seems to be no implementation for storing per-calendar settings in Etar?
3. Another approach is to implement per-calendar notification channels. For a user point of view this is the most flexible as one has full control over notification settings. 

Maybe (1) should be implemented anyway and then either (2) or (3)?
Any ideas?

**Comment by runejuhl** [comment]
Thank you for looking into this @ploink!

> Another approach is to implement per-calendar notification channels. For a user point of view this is the most flexible as one has full control over notification settings.

IMO this sounds like the most sensible (and flexible) approach.

Do you know if there are other calendar apps (free or not) that are able to disable notifications per calendar, and if so, how do they do it?

**Comment by shompoe** [comment]
Yes!   

Simple Calendar Pro.

This is not an option within the app but it already uses a separate notification channel as mentioned above. Works very well for me. After recieving the first reminder for a calendar, the channel appears in android settings to disable it.

**Comment by runejuhl** [comment]
@shompoe thank you -- sounds like separate notification channels are the way to go then.

I only have a little bit of Android development experience, and it's a LNG time ago, but I'd be happy to help review/clean up/document a patch that adds this feature to Etar.

**Comment by akki42** [comment]
My [similar request](https://github.com/Etar-Group/Etar-Calendar/issues/67) has unfortunately been open since 2016...

[Calendar Notification](https://github.com/quarck/CalendarNotification) or [Calendar Notification NG](https://github.com/quarck/CalendarNotificationNG) previously provided a third-party app workaround, but have been discontinued.

**Comment by madduck** [comment]
I also just came here to file such a request… using notification channels would be the way to go. Unfortunately, Simple Calendar is quite buggy with alarms it seems, and I love the Etar UI and feel more anyway.

**Comment by Inrumpo** [comment]
I'm experiencing a similar issue: I'm getting reminders from an online calendar I've subscribed to. I'd like to be able to turn those off.
