### ISSUE TITLE
Can no longer change calendar?

### ISSUE THREAD

**Issue by FreeJulianAssange** [Etar-Group/Etar-Calendar#812]
I came to report that in the last 1-2 weeks, I lost the ability to edit the calendar of an existing event.
To my surprise, it seems this feature isn't even present in Etar, but has been requested.

However, I swear I have been using this feature for the last few months?
I only lost the ability in the last couple of weeks but I'm not sure which of the recent updates from DAVx5 or Etar that stopped it working.

I use Etar, DAVx5 & Nextcloud....previously in Etar, I could tap an _event > edit > tap calendar name > drop down_ menu to select the calendar I want to change the event to.

Now I just feel crazy???

Huawei LYA-L29
Android 10
Etar 1.0.23

**Comment by jedie** [comment]
I miss this feature, too.

**Comment by jedie** [comment]
https://f-droid.org/packages/com.simplemobiletools.calendar.pro/ can move existing entries from one calendar to a other one.

**Comment by reox** [comment]
> However, I swear I have been using this feature for the last few months?

I'm not sure if I'm remembering wrong but I feel the same. I'm pretty sure I switched some entries which were added in the wrong calendar but this is not working anymore.

**Comment by brunetton** [comment]
New to Etar, I'm using it for a few days now. I've 4 Google calendars and I'm very surprised to see that I can choose on witch calendar I put a new event while creating it, but I can't move a previously created one from one calendar to another.

I really miss this feature. As a workaround for now I delete the "wrong" one, create another one with the same data, in the correct calendar, and delete the first one.. Long process, especially when I filled many fields (description, begin and end times, etc)

Do you plan to implement this feature? 

Thanks

**Comment by jeremymeyers** [comment]
+1

**Comment by peterprumbach** [comment]
Hey, is there any plan, when this feature will be available again?

**Comment by tiptoptom** [comment]
See #62
