### ISSUE TITLE
Appointment sync

### ISSUE THREAD

**Issue by grizzly8u** [Etar-Group/Etar-Calendar#849]
Entered appointment on calendar (caldav sync) and doesn't appear on device. Similarly entered appointment on device with attendee added and doesn't appear in my mailbox.org calendar on desktop. Device is BlackBerry Keyone and desktop is MxLinux.

**Comment by jspricke** [comment]
Etar only displays calendars, you need an extra app to sync them. See: https://github.com/Etar-Group/Etar-Calendar#how-to-use-etar

**Comment by grizzly8u** [comment]
I use caldav with a mailbox.org calendar. It finally synced so I'm not
sure where the holdup was. Also, it appears that you cannot edit
attendee's to an event. Thanks,
