### ISSUE TITLE
package com.android.common does not exist

### ISSUE THREAD

**Issue by elig0n** [Etar-Group/Etar-Calendar#853]
I'm trying to build Etar-Calendar on Android Studio 4.1.2 / gradle 6.7 but it complains that (one along many):

```
Etar-Calendar/src/com/android/calendar/CalendarEventModel.java:32: error: package com.android.common does not exist
import com.android.common.Rfc822Validator;
                         ^
```

**Comment by jspricke** [comment]
did you follow the build instructions?
https://github.com/Etar-Group/Etar-Calendar#build-instructions

**Comment by elig0n** [comment]
yes but I probably messed up something. I recloned and it's working now
