### ISSUE TITLE
Please add "duplicate event" option

### ISSUE THREAD

**Issue by GBT7** [Etar-Group/Etar-Calendar#877]
Title. It would be great to simply duplicate events to different days or different calendars, and also to have an option to move existing events to different calendars. Google Calendar has this option and it is very useful.

**Comment by gthbusrr** [comment]
I second this!!!

**Comment by stephan75** [comment]
Moving an event to another calendar is also available in **"SimpleCalendar"**.

https://github.com/SimpleMobileTools/Simple-Calendar

Shame on my for the idea to have a closer look at its source code in that app and how they enabled that feature of moving an event to another calendar?

**Comment by KeronCyst** [comment]
I concur.

**Comment by SilverPuppy** [comment]
This has now been done. https://github.com/Etar-Group/Etar-Calendar/issues/87

**Comment by SilverPuppy** [comment]
Completed in https://github.com/Etar-Group/Etar-Calendar/pull/1248
