### ISSUE TITLE
Days of the week [still] cut off

### ISSUE THREAD

**Issue by hobas** [Etar-Group/Etar-Calendar#887]
I found a thread which describes my problem: the days of the week are cut off (#506)
It is marked closed by now, but unfortunately the problem still persists for me.

Android 7.1.2
Etar 1.0.25
Device: Xoro MegaPAD 1404V4

**Comment by Metaboson** [comment]
Same here.
Etar 1.0.24
Android 8.1.0
Device: Samsung SM-T830

**Comment by hobas** [comment]
Fixed. Thank you!
