### ISSUE TITLE
Bug? etar 1.0.25 and 1.0.21: no notification or event if Google Calendar is disabled, and local only db

### ISSUE THREAD

**Issue by pickeduname** [Etar-Group/Etar-Calendar#896]
etar 1.0.25 and 1.0.21 on 8.1 resp. 4.4, presumably also all in between versions, no others tested:   
*No notification or event if Google Calendar is disabled, and only local calendar db is available.*  
This was tested on 2 devices as above, neither is rooted.

*Expected behavior and test setup:* Disable `Google Calendar` in `Settings`. Set an `etar` event for now+5 minutes for example, save to `local calendar db` (all accounts/other calendar db's disabled in etar Settings). When the set time comes up, a notification and a sound are expected. Notifications are enabled in OS Settings for etar.

Found behavior: no notification, no sound, no alarm when the time comes up, if the Google Calendar application is disabled in OS Settings. If the application is not disabled, then the notification/event opens Google Calendar (not desirable with etar events and only offline calendar database present).

Suggested fix: make etar play a sound itself, and generate a notification itself in this case. Note in 1.0.21 the sound is selectable but still no sound is made on event. In 1.0.25 the sound is not directly selectable in Settings but is also not generated (default notification sound set by system).

Note: imo there is no point for an offline / google less calendar app if it fires up Google Calendar at the specified time, and by that, also sends the calendar event to the cloud. Google-less operation should be tested throughly for this reason imo. Thanks.

**Comment by jspricke** [comment]
Etar does not use the Google Calendar in any way (I don't have it installed and get notifications just fine).
Your problem rather sounds like the Android OS is getting in the way and suspends Etar so it can't issue the notification. Depending on your OS version there are options to disable this (battery optimization).
