### ISSUE TITLE
Support URL field as an extended property [feature request]

### ISSUE THREAD

**Issue by devvv4ever** [Etar-Group/Etar-Calendar#903]
Hello everyone,

DAVx5 has now support for synchronizing URL fields. So it would be cool if etar could support this field, too. Currently people use the description field for storing for example video call URLs but a dedicated URL field would be much more straightforward for this. 

Since this would be an extended property not covered by Android itself we have put some information together how this is implemented and stored. Please have a look here:

https://www.davx5.com/manual/integration.html#extended-event-properties

At the moment there are only a few servers or other clients that support it (icloud / Apple, Evolution on Linux, acalendar+ on Android, and a few more), so it would be cool if etar users would be able to use this field, too. It would also improve the calendar ecosystem in general.

Kind regards,
Bernhard / DAVx5

**Comment by jluttine** [comment]
Yes, I would love this very much too! Just a comment that the support would hopefully include both editing/viewing calendar events in the calendar and also importing ICS files with URL fields.

**Comment by jluttine** [comment]
Yes, I would love this very much too! Just a comment that the support would hopefully include both editing/viewing calendar events in the calendar and also importing ICS files with URL fields.

Here is the specification link: https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.4.6
