### ISSUE TITLE
Have you considered changing the month view to sliding left and right? The current way of sliding up and down is a bit inconvenient and not easy to control.  The month view that swipes left and right is similar to the way that Google Calendar or tick list operates.  This will greatly improve the user experience

### ISSUE THREAD

**Issue by 9292922** [Etar-Group/Etar-Calendar#905]

**Comment by 9292922** [comment]
Have you considered changing the month view to sliding left and right? The current way of sliding up and down is a bit inconvenient and not easy to control.  The month view that swipes left and right is similar to the way that Google Calendar or tick list operates.  This will greatly improve the user experience

**Comment by 9292922** [comment]
> 

As the title.

**Comment by ueen** [comment]
Disagree, please keep it like this, way better than horizontal! 😊😊

**Comment by elig0n** [comment]
I like the current way but maybe a right or left swipe could be bound to move months in blocks instead?

**Comment by toolstack** [comment]
I liked @elig0n's idea of left/right swiping to move between months so I created PR #1479 to add it.

**Comment by jooooscha** [comment]
Just went back to version 36 because of this. I really don't like the swipe gestures. In fact, I am using this app because it is the only calendar app that does not have the (in my opinion impractical) swipe left/right view. I really like that with etar you can view half of one month on the top and half of the next month on the bottom.

At least for me the swipe gesture is just annoying when scrolling up and down. So could I ask for making the swipe gestures optional with a disable button in the options?

**Comment by 9292922** [comment]
You can optionally swipe up and down or swipe left and right



---Original---
From: ***@***.***&gt;
Date: Fri, Feb 16, 2024 06:38 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Etar-Group/Etar-Calendar] Have you considered changing the monthview to sliding left and right? The current way of sliding up and down is abit inconvenient and not easy to control.  The month view that swipes left andright is similar to the way that Google Calendar or tick list operates.  Thiswill greatly improve the user experience (#905)




 
Just went back to version 36 because of this. I really don't like the swipe gestures. In fact, I am using this app because it is the only calendar app that does not have the (in my opinion impractical) swipe left/right view. I really like that with etar you can view half of one month on the top and half of the next month on the bottom.
 
At least for me the swipe gesture is just annoying when scrolling up and down. So could I ask for making the swipe gestures optional with a disable button in the options?

**Comment by jooooscha** [comment]
As I wrote before, the new left/right swipe gesture often interfere with the up/down scrolling, and I end up not half a month up but instead a whole month or even 2 months up. That is very annoying to the point where the current implementation is unusable for me.

Therefore, I would really like to have an option to disable the new left/right swipe gestures.
