### ISSUE TITLE
Rename app name

### ISSUE THREAD

**Issue by thenktor** [Etar-Group/Etar-Calendar#910]
Hi,

the app is just called "Etar" on my phone with KISS launcher. IMHO it should be named "Etar Calendar" (and translated to the device language).

**Comment by jspricke** [comment]
afaik there is no subtitle, what you mean is added by the KISS launcher: https://github.com/Neamar/KISS/blob/master/app/src/main/res/values/strings.xml#L104

**Comment by thenktor** [comment]
Indeed :+1:
