### ISSUE TITLE
Weird characters after translated string.

### ISSUE THREAD

**Issue by jakubfabijan** [Etar-Group/Etar-Calendar#918]
After the translated Esperanto string for "today" - "hodiaŭ" there are characters that doesn't suppose to be there.
![Screenshot_20210517-120406.png](https://user-images.githubusercontent.com/53099243/118472063-b937df00-b708-11eb-9d49-4f0be1bd2394.png) I checked and it isn't the translation mistake on Weblate.

**Comment by jakubfabijan** [comment]
Anybody?

**Comment by jspricke** [comment]
Looks like they are in the translation: https://github.com/Etar-Group/Etar-Calendar/blob/master/res/values-eo/strings.xml#L16

Btw. please don't ping bugs.

**Comment by jakubfabijan** [comment]
> Btw. please don't ping bugs.

sorry

> Looks like they are in the translation

![screenshot](https://user-images.githubusercontent.com/53099243/120113124-4fdcb500-c179-11eb-8b89-5160e113fde8.png)
the thing is that it's (i think) some kind of variable, it works normally in English, i have no idea why not in esperanto
