### ISSUE TITLE
Dynamic icon

### ISSUE THREAD

**Issue by ueen** [Etar-Group/Etar-Calendar#920]
Could you add an dynamic icon? So that the current date is displayed on the homescreen?
That would make the app perfect! 

Maybe you could take inspiration from this https://github.com/Katecca/android-dynamic-app-icon
https://stackoverflow.com/questions/34592230/is-there-any-way-to-dynamically-change-an-app-icon-like-calendar-app-does

**Comment by UserX404** [comment]
Hi @ueen 
Github is handled as issue tracker.
Please search for existing feature request at the [community forum](https://community.signalusers.org/). (Or create an new one if nothing exists).

**Comment by jspricke** [comment]
@UserX404 this is the Etar issue tracker and not related to Signal.

**Comment by jspricke** [comment]
duplicates #711.

**Comment by UserX404** [comment]
Ooooh damn, sorry.
I hadn't recognized the etar-headline. My fault. :-S
