### ISSUE TITLE
No exchange support?

### ISSUE THREAD

**Issue by studied-sermon-gender** [Etar-Group/Etar-Calendar#929]
Hi,

in the F-Droid describtion there is written that it has Exhnage support. But how do I activate this? In the app, I can only see CalDAV, EteSync or offline calendars. 
How can I use my MS Exchange calender with Etar? Or is it even possible?

Thanks

**Comment by jspricke** [comment]
The description states: "Works with Google Calendar, Exchange, etc" not that it has Exchange support.
You need an Exchange sync adapter, normally provided by the Android system. Please read the details here:
https://github.com/Etar-Group/Etar-Calendar#how-to-use-etar
