### ISSUE TITLE
Synchronization with Google iCal secret address

### ISSUE THREAD

**Issue by GEkuL** [Etar-Group/Etar-Calendar#947]
Hello there,

Google has this feature in calendar's settings "Secret address in iCal format". 
![image](https://user-images.githubusercontent.com/42621207/124104408-ecd98900-da6a-11eb-881e-ff9472080379.png)

So it seems like the easiest way to make synchronisation with google.

Could you provide this option in the app?

**Comment by jspricke** [comment]
Etar does not sync calendars (it does not even have permission to access the net), maybe some sync program can do that, also see: https://github.com/Etar-Group/Etar-Calendar#how-to-use-etar
