### ISSUE TITLE
There's no option to use a fully offline calendar at start

### ISSUE THREAD

**Issue by OutshineIssue** [Etar-Group/Etar-Calendar#948]
The app keeps asking me for calendar permission, I don't want to give this permission, I want a fully local calendar, no sync at all. If I block the request, the app crashes.
And I know I can give the permission, unsync all my accounts and then create an offline calendar, but why? Why do we have to do this to begin with? My accounts keep showing up in settings and it makes me uncomfortable to see them when I only want my calendar to be on my phone and only on my phone.

**Comment by jspricke** [comment]
Etar does not have an internal database for events but uses the one provided by the Android system and thus needs the permission. See: https://github.com/Etar-Group/Etar-Calendar#technical-explanation

**Comment by OutshineIssue** [comment]
I see but it really needs to fetch all my Google/Outlook accounts? It can't just ask me what to do next?

**Comment by jspricke** [comment]
Etar does not fetch anything (it does not even have permission to connect to the Internet). All it does is showing and modifying what is already on you phone.
