### ISSUE TITLE
adding guests email with a plus "+" in the email address crashes app

### ISSUE THREAD

**Issue by etar-user** [Etar-Group/Etar-Calendar#981]
adding an 
email address containing a + in the "event guests" field causes etar to crash.
I tested with example+crash@example.com
![Screenshot_20210825-133610_Etar](https://user-images.githubusercontent.com/89536975/130839366-c59c9d8c-d9b1-4e76-b5b3-b4483da61743.jpg)

running v1.0.26

**Comment by kavitamp** [comment]
Hi @Gitsaibot,
You can close the issue as it is fixed & the PR is merged:
https://github.com/Etar-Group/android_frameworks_opt_chips/pull/2
